*--- MAIN PROGRAM: FZMM_TEND_BNCDV ---*
* declaration for the long text
DATA: BEGIN OF ICDTXT_ZMM_TEND_BN OCCURS 20.
        INCLUDE STRUCTURE CDTXT.
DATA: END OF ICDTXT_ZMM_TEND_BN.
DATA: UPD_ICDTXT_ZMM_TEND_BN TYPE C.

* workaera_old of ZMM_PUR_TENDER_D
TABLES: *ZMM_PUR_TENDER_D
* workaera_new of ZMM_PUR_TENDER_D
       , ZMM_PUR_TENDER_D.
DATA: UPD_ZMM_PUR_TENDER_D TYPE C.

