*--- MAIN PROGRAM: FZPR_RCPT_DTCDV ---*
* declaration for the long text
DATA: BEGIN OF ICDTXT_ZPR_RCPT_DT OCCURS 20.
        INCLUDE STRUCTURE CDTXT.
DATA: END OF ICDTXT_ZPR_RCPT_DT.
DATA: UPD_ICDTXT_ZPR_RCPT_DT TYPE C.

* workaera_old of ZMM_TMS
TABLES: *ZMM_TMS
* workaera_new of ZMM_TMS
       , ZMM_TMS.
DATA: UPD_ZMM_TMS TYPE C.

