*--- MAIN PROGRAM: MZM06B_OFAC ---*
  INCLUDE MM06BFAC_AVAILABILITY_CHECK ." AVAILABILITY_CHECK

  INCLUDE MM06BFAC_AC_INITIAL_CHECKS . " AC_INITIAL_CHECKS

  INCLUDE MM06BFAC_AC_REFRESH_INTERNAL_T .  " AC_REFRESH_INTERNAL_TABLES

  INCLUDE MM06BFAC_AC_ATPCS_NEW_ENTRY ." AC_ATPCS_NEW_ENTRY

  INCLUDE MM06BFAC_AC_ATPCS_SAME_MATERIA .  " AC_ATPCS_SAME_MATERIAL

  INCLUDE MM06BFAC_AC_SORT_ATPCS .     " AC_SORT_ATPCS

  INCLUDE MM06BFAC_AC_CALL_ATP_CONTROLLE .  " AC_CALL_ATP_CONTROLLER

  INCLUDE MM06BFAC_AC_DIALOG .         " AC_DIALOG

  INCLUDE MM06BFAC_AC_DETERMINE_TRTYP ." AC_DETERMINE_TRTYP

  INCLUDE MM06BFAC_AC_SHOW_ATP_SCREEN ." AC_SHOW_ATP_SCREEN

  INCLUDE MM06BFAC_AC_COMMITTED_QTY .  " AC_COMMITTED_QUANTITIES

  INCLUDE MM06BFAC_AC_GET_DB_VALUES .  " AC_GET_DB_VALUES
