*--- MAIN PROGRAM: MZM06B_OI0R ---*
  INCLUDE MM06BI0R_REF_EXIT .  " REF_EXIT

  INCLUDE MM06BI0R_RESWK .  " RESWK

  INCLUDE MM06BI0R_RFT_BLAETTERN .  " RFT_BLAETTERN

  INCLUDE MM06BI0R_RFT_POSITION .  " RFT_POSITION

  INCLUDE MM06BI0R_RFT_PRUEFEN .  " RFT_PRUEFEN

  INCLUDE MM06BI0R_RFT_SEL .  " RFT_SEL

  INCLUDE MM06BI0R_RFT_SEL_MERKEN .  " RFT_SEL_MERKEN

  INCLUDE MM06BI0R_RM06B_REFBN .  " RM06B_REFBN

  INCLUDE MM06BI0R_REQUEST_KZ .  " REQUEST_KZ

  INCLUDE MM06BI0R_REVISIONSSTAND .  " REVISIONSSTAND

*end of mm06bi01 ******************************************************
