*--- MAIN PROGRAM: MZM06B_OIOI ---*
  INCLUDE MM06BIOI_CLEAR_OITAXFROM .  " CLEAR_OITAXFROM

  INCLUDE MM06BIOI_CHECK_OIHANTYPE .  " CHECK_OIHANTYPE

  INCLUDE MM06BIOI_INIT_FLAGS .  " INIT_FLAGS

  INCLUDE MM06BIOI_TDP_DEFAULT .  " TDP_DEFAULT
