*--- MAIN PROGRAM: MZM06B_OFDA ---*
  INCLUDE MM06BFDA_DELIVERY_ADDRE03 .  " DELIVERY_ADDRESS

  INCLUDE MM06BFDA_DELIVERY_ADDRESS .  " DELIVERY_ADDRESS

  INCLUDE MM06BFDA_DELIVERY_ADDR_NUMBERS .  " DELIVERY_ADDR_NUMBERS_GET

  INCLUDE MM06BFDA_DELIVERY_ADDRESS_CO02 .  " DELIVERY_ADDRESS_COPY

  INCLUDE MM06BFDA_DELIVERY_ADDRESS_COPY .  " DELIVERY_ADDRESS_COPY_FROM

  INCLUDE MM06BFDA_DELIVERY_ADDRESS_INIT .  " DELIVERY_ADDRESS_INIT
