*--- MAIN PROGRAM: MZM06B_OI0B ---*
*eject
***********************************************************************
*         PAI-Module  MM06BI0B   Bestellanforderungen                 *
*         Alphabetisch geordnet; hier beginnned mit 'B'               *
***********************************************************************

  INCLUDE MM06BI0B_BADAT .  " BADAT

  INCLUDE MM06BI0B_BERECHTIGUNGEN_POS .  " BERECHTIGUNGEN_POS

  INCLUDE MM06BI0B_BEZUGSQUELLE_1 .  " BEZUGSQUELLE_1


  INCLUDE MM06BI0B_BEZUGSQUELLE_2 .  " BEZUGSQUELLE_2

  INCLUDE MM06BI0B_BMEIN .  " BMEIN


  INCLUDE MM06BI0B_BSC_BLAETTERN .  " BSC_BLAETTERN

  INCLUDE MM06BI0B_BSC_FUELLEN_EINZEL .  " BSC_FUELLEN_EINZEL

  INCLUDE MM06BI0B_BSC_FUELLEN_LOOP .  " BSC_FUELLEN_LOOP

  INCLUDE MM06BI0B_BSC_PRUEFEN .  " BSC_PRUEFEN

  INCLUDE MM06BI0B_BSC_PRUEFEN_EINZEL .  " BSC_PRUEFEN_EINZEL

  INCLUDE MM06BI0B_BSC_REQUEST .  " BSC_REQUEST


  INCLUDE MM06BI0B_BSC_SUBSCREEN_GET .  " BSC_SUBSCREEN_GET

  INCLUDE MM06BI0B_BSC_SUBSCREEN_PUT .  " BSC_SUBSCREEN_PUT

  INCLUDE MM06BI0B_BSC_WIEDERH_EINZEL .  " BSC_WIEDERH_EINZEL

  INCLUDE MM06BI0B_BSN_BLAETTERN .  " BSN_BLAETTERN

  INCLUDE MM06BI0B_BSN_BLAETTERN_POP .  " BSN_BLAETTERN_POP

  INCLUDE MM06BI0B_BSN_FUELLEN .  " BSN_FUELLEN

  INCLUDE MM06BI0B_BSN_LESEN_KEY .  " BSN_LESEN_KEY

  INCLUDE MM06BI0B_BSNB_BLAETTERN .  " BSNB_BLAETTERN

  INCLUDE MM06BI0B_BSNB_PICK .  " BSNB_PICK

  INCLUDE MM06BI0B_BSC_CHECK_SAKTO .  " BSC_CHECK_SAKTO


  INCLUDE MM06BI0B_BSC_COBL_FULL_SCREEN .  " BSC_COBL_FULL_SCREEN


  INCLUDE MM06BI0B_BSCB_FCODE .  " BSCB_FCODE


  INCLUDE MM06BI0B_BSC_UNTERLEGEN .  " BSC_UNTERLEGEN

  INCLUDE MM06BI0B_BSC_KNTTP_CHANGE .  " BSC_KNTTP_CHANGE


  INCLUDE MM06BI0B_BSCB_CHECK .  " BSCB_CHECK
*end of MM06BI0B ******************************************************
