*--- MAIN PROGRAM: MZM06B_OFOI ---*
  INCLUDE MM06BFOI_POPULATE_TDP .  " POPULATE_TDP

  INCLUDE MM06BFOI_READ_INFO_2 .  " READ_INFO_2

  INCLUDE MM06BFOI_DEF_VAL_HANTYP .  " DEF_VAL_HANTYP

  INCLUDE MM06BFOI_HANTYP_VALIDATION .  " HANTYP_VALIDATION

  INCLUDE MM06BFOI_READ_INFO .  " READ_INFO

  INCLUDE MM06BFOI_INFO_REC_DEFAULT .  " INFO_REC_DEFAULT

  INCLUDE MM06BFOI_VENDOR_DEFAULT .  " VENDOR_DEFAULT

  INCLUDE MM06BFOI_OIH08_DEFAULT .  " OIH08_DEFAULT

  INCLUDE MM06BFOI_MARC_LOOKUP .  " MARC_LOOKUP

  INCLUDE MM06BFOI_VAL_INEX .  " VAL_INEX

  INCLUDE MM06BFOI_VENDOR_HANTYP_LOOKUP .  " VENDOR_HANTYP_LOOKUP

  INCLUDE MM06BFOI_DEF_VAL_TYPE .  " DEF_VAL_TYPE


  INCLUDE MM06BFOI_INFO_RECORD_DEFAULT .  " INFO_RECORD_DEFAULT

  INCLUDE MM06BFOI_OI001_DEFAULT .  " OI001_DEFAULT

  INCLUDE MM06BFOI_VAL_INEX_DEFAULT .  " VAL_INEX_DEFAULT

  INCLUDE MM06BFOI_TDP_DEFAULT .  " TDP_DEFAULT

  INCLUDE MM06BFOI_FILL_TDP_RFT_1 .  " FILL_TDP_RFT_1

  INCLUDE MM06BFOI_DEFVAL_HANTYP .  " DEFVAL_HANTYP

  INCLUDE MM06BFOI_OPEN_FIELD .  " OPEN_FIELD
