*--- MAIN PROGRAM: MZM06B_OFMS ---*
  INCLUDE MM06BFMS_DIEN_FCODE .  " DIEN_FCODE

  INCLUDE MM06BFMS_DIEN_MAINTAIN .  " DIEN_MAINTAIN

  INCLUDE MM06BFMS_DIEN_VERBUCHEN .  " DIEN_VERBUCHEN


  INCLUDE MM06BFMS_SET_SRV_VALUES .  " SET_SRV_VALUES

  INCLUDE MM06BFMS_GET_SRV_VALUES .  " GET_SRV_VALUES


  INCLUDE MM06BFMS_SET_KNT_VALUES .  " SET_KNT_VALUES


  INCLUDE MM06BFMS_GET_KNT_VALUES .  " GET_KNT_VALUES

  INCLUDE MM06BFMS_CHECK_MUSTER_LV .  " CHECK_MUSTER_LV

  INCLUDE MM06BFMS_FILL_RFT .  " FILL_RFT
