*--- MAIN PROGRAM: MZM06B_OFRF ---*
*eject
************************************************************************
* Unterroutinen fuer Bearbeitung interne Tabelle RFT (Referenzbearb.)  *
************************************************************************

  INCLUDE MM06BFRF_RFT_ABBRECHEN .  " RFT_ABBRECHEN

  INCLUDE MM06BFRF_RFT_AUFBAUEN .  " RFT_AUFBAUEN

  INCLUDE MM06BFRF_RFT_BLAETTERN .  " RFT_BLAETTERN

  INCLUDE MM06BFRF_RFT_EINGABEN .  " RFT_EINGABEN

  INCLUDE MM06BFRF_RFT_FIRST .  " RFT_FIRST

  INCLUDE MM06BFRF_RFT_INIT .  " RFT_INIT

  INCLUDE MM06BFRF_RFT_NEXT_KEY .  " RFT_NEXT_KEY

  INCLUDE MM06BFRF_RFT_NEXT_REF .  " RFT_NEXT_REF

  INCLUDE MM06BFRF_RFT_LESEN_KEY .  " RFT_LESEN_KEY

  INCLUDE MM06BFRF_RFT_LESEN_LOOP .  " RFT_LESEN_LOOP

  INCLUDE MM06BFRF_RFT_POSITION .  " RFT_POSITION

  INCLUDE MM06BFRF_RFT_PRUEFEN .  " RFT_PRUEFEN

  INCLUDE MM06BFRF_RFT_SEL .  " RFT_SEL

  INCLUDE MM06BFRF_RFT_SEL_MARK .  " RFT_SEL_MARK

  INCLUDE MM06BFRF_RFT_SEL_MERKEN .  " RFT_SEL_MERKEN

  INCLUDE MM06BFRF_RFT_SEL_MERKEN_VOR .  " RFT_SEL_MERKEN_VOR

  INCLUDE MM06BFRF_RFT_UPDATE .  " RFT_UPDATE

  INCLUDE MM06BFRF_RFT_VORSELEKTION .  " RFT_VORSELEKTION

  INCLUDE MM06BFRF_RFT_XPRE02 .  " RFT_XPRE02
