*--- MAIN PROGRAM: MZM06B_OFLB ---*
  INCLUDE MM06BFLB_MDPM_CALL .  " MDPM_CALL

  INCLUDE MM06BFLB_MDPM_MAINTAIN .  " MDPM_MAINTAIN

  INCLUDE MM06BFLB_MDPM_VERBUCHEN .  " MDPM_VERBUCHEN

  INCLUDE MM06BFLB_MDPM_NUMBER .  " MDPM_NUMBER
