*--- MAIN PROGRAM: MZM06B_OI0C ---*
  INCLUDE MM06BI0C_CALL_EBANPOS .  " CALL_EBANPOS

  INCLUDE MM06BI0C_CALL_DIEN .  " CALL_DIEN

  INCLUDE MM06BI0C_CALL_D0104 .  " CALL_D0104

  INCLUDE MM06BI0C_CALL_KOMPONENTEN .  " CALL_KOMPONENTEN

  INCLUDE MM06BI0C_CHECK_MANDATORY_FIELD .  " CHECK_MANDATORY_FIELDS

  INCLUDE MM06BI0C_CLEAR_ZEILE .  " CLEAR_ZEILE

  INCLUDE MM06BI0C_CONVERT_SELFLAG .  " CONVERT_SELFLAG
