*--- MAIN PROGRAM: MZM06B_OFBN ---*
*eject
************************************************************************
* Unterroutinen zur Bearbeitung der internen Tabelle BSN               *
************************************************************************
* 76753 12.08.1997      CF
* 84003 15.10.1997 3.1I GT : Bestellanforderung für MRP nicht fixiert
* 88865 22.01.1998 3.1I CF : Cursorpositionierung nach Detailfunktion
* 96155 19.02.1998 4.0C SM : keine gelöschten Pos. bei ME54

  INCLUDE MM06BFBN_BSNA_CHECK_POST .  " BSNA_CHECK_POST

  INCLUDE MM06BFBN_BSNA_DELETE .  " BSNA_DELETE

  INCLUDE MM06BFBN_BSNA_INSERT .  " BSNA_INSERT

  INCLUDE MM06BFBN_BSNA_READ .  " BSNA_READ

  INCLUDE MM06BFBN_BSN_AUFBAUEN .  " BSN_AUFBAUEN

  INCLUDE MM06BFBN_BSN_BLAETTERN .  " BSN_BLAETTERN

  INCLUDE MM06BFBN_BSN_BLAETTERN_POP .  " BSN_BLAETTERN_POP

  INCLUDE MM06BFBN_BSN_ESTKZ .  " BSN_ESTKZ

  INCLUDE MM06BFBN_BSN_FIRST .  " BSN_FIRST

  INCLUDE MM06BFBN_BSN_FUELLEN .  " BSN_FUELLEN

  INCLUDE MM06BFBN_BSN_FUELLEN_REF .  " BSN_FUELLEN_REF

  INCLUDE MM06BFBN_BSN_LESEN_KEY .  " BSN_LESEN_KEY

  INCLUDE MM06BFBN_BSN_LESEN_LOOP .  " BSN_LESEN_LOOP

  INCLUDE MM06BFBN_BSN_LOESCHEN .  " BSN_LOESCHEN

  INCLUDE MM06BFBN_BSN_PRUEFEN .  " BSN_PRUEFEN
