*--- MAIN PROGRAM: MZM06B_OFBC ---*
*eject
* 92045 TK 4.0B 8.1.98 Mußfelder auf Kontierungsblock
************************************************************************
* Unterroutinen fuer Bearbeitung Tabelle BSC                           *
************************************************************************


  INCLUDE MM06BFBC_BSC_ABBRECHEN .  " BSC_ABBRECHEN

  INCLUDE MM06BFBC_BSC_AUFBAUEN .  " BSC_AUFBAUEN

  INCLUDE MM06BFBC_BSC_AUFBAUEN_REF .  " BSC_AUFBAUEN_REF

  INCLUDE MM06BFBC_BSC_BLAETTERN .  " BSC_BLAETTERN

  INCLUDE MM06BFBC_BSC_ENDE .  " BSC_ENDE

  INCLUDE MM06BFBC_BSC_FIRST .  " BSC_FIRST


  INCLUDE MM06BFBC_BSC_FUELLEN .  " BSC_FUELLEN

  INCLUDE MM06BFBC_BSC_FUELLEN_EINZEL .  " BSC_FUELLEN_EINZEL

  INCLUDE MM06BFBC_BSC_FUELLEN_LOOP .  " BSC_FUELLEN_LOOP

  INCLUDE MM06BFBC_BSC_FUELLEN_REF .  " BSC_FUELLEN_REF

  INCLUDE MM06BFBC_BSC_INIT .  " BSC_INIT

  INCLUDE MM06BFBC_BSC_LESEN_EINZEL .  " BSC_LESEN_EINZEL

  INCLUDE MM06BFBC_BSC_LESEN_LOOP .  " BSC_LESEN_LOOP

  INCLUDE MM06BFBC_BSC_LOESCHEN .  " BSC_LOESCHEN


  INCLUDE MM06BFBC_BSC_PRUEFEN .  " BSC_PRUEFEN


  INCLUDE MM06BFBC_BSC_REF .  " BSC_REF

  INCLUDE MM06BFBC_BSC_WIEDERHOLEN_EINZE .  " BSC_WIEDERHOLEN_EINZEL

  INCLUDE MM06BFBC_BSC_WIEDERHOLEN .  " BSC_WIEDERHOLEN

  INCLUDE MM06BFBC_BSC_WIEDERHOLEN_AUS .  " BSC_WIEDERHOLEN_AUS

  INCLUDE MM06BFBC_BSC_WIEDERHOLEN_EIN .  " BSC_WIEDERHOLEN_EIN

  INCLUDE MM06BFBC_BSC_INT_COBLF_FUELLEN .  " BSC_INT_COBLF_FUELLEN

  INCLUDE MM06BFBC_BSC_COBL_FUELLEN .  " BSC_COBL_FUELLEN


  INCLUDE MM06BFBC_BSC_SUBSCREEN_SETZEN .  " BSC_SUBSCREEN_SETZEN



  INCLUDE MM06BFBC_BSC_SUBSCREEN_PUT .  " BSC_SUBSCREEN_PUT


  INCLUDE MM06BFBC_BSC_SUBSCREEN_GET .  " BSC_SUBSCREEN_GET


  INCLUDE MM06BFBC_BSC_CHECK_SAKTO .  " BSC_CHECK_SAKTO

  INCLUDE MM06BFBC_BSC_BILD_HALTEN .  " BSC_BILD_HALTEN


  INCLUDE MM06BFBC_BSC_COBL_FULL_SCREEN .  " BSC_COBL_FULL_SCREEN

  INCLUDE MM06BFBC_BSC_COBL_PRUEFEN .  " BSC_COBL_PRUEFEN



  INCLUDE MM06BFBC_BSC_PRUEFEN_EINZEL .  " BSC_PRUEFEN_EINZEL

  INCLUDE MM06BFBC_BSC_COBL_UEBERNEHMEN .  " BSC_COBL_UEBERNEHMEN

  INCLUDE MM06BFBC_BSC_REQUEST .  " BSC_REQUEST


  INCLUDE MM06BFBC_BSC_UPDATE .  " BSC_UPDATE


  INCLUDE MM06BFBC_CHECK_AUSWAHL_KONTIER .  " CHECK_AUSWAHL_KONTIERUNG

  INCLUDE MM06BFBC_BSC_KNTTP_CHANGE .  " BSC_KNTTP_CHANGE

  INCLUDE MM06BFBC_BSC_CHECK_KZBWS .  " BSC_CHECK_KZBWS


  INCLUDE MM06BFBC_BSC_CHANGE_BWTAR .  " BSC_CHANGE_BWTAR

  INCLUDE MM06BFBC_BSC_CHANGE_MATKL .  " BSC_CHANGE_MATKL
  INCLUDE MM06BFBC_KZBWS_CHECK_SAKTO .  " KZBWS_CHECK_SAKTO

  INCLUDE MM06BFBC_BSC_INIT_ASSET_FIELDS .  " BSC_INIT_ASSET_FIELDS

  INCLUDE MM06BFBC_BSC_RWIN_AUFRUF .  " BSC_RWIN_AUFRUF



  INCLUDE MM06BFBC_BSC_ANLA_GENERATE .  " BSC_ANLA_GENERATE

  INCLUDE MM06BFBC_BSC_DUMMY_BILD_SENDEN .  " BSC_DUMMY_BILD_SENDEN

  INCLUDE MM06BFBC_BSC_SACHKONTO_PRUEFEN .  " BSC_SACHKONTO_PRUEFEN


  INCLUDE MM06BFBC_BSC_CHECK_MANDATORY_F .  " BSC_CHECK_MANDATORY_FIELDS


  INCLUDE MM06BFBC_BSC_ANLA_NUMBER_CHANG .  " BSC_ANLA_NUMBER_CHANGE
  INCLUDE MM06BFBC_BSC_VORNR_SETZEN .  " BSC_VORNR_SETZEN

  INCLUDE MM06BFBC_BSC_SAKTO_VORSCHLAGEN .  " BSC_SAKTO_VORSCHLAGEN


  INCLUDE MM06BFBC_BSC_GRPG_CHECK .  " BSC_GRPG_CHECK
