*--- MAIN PROGRAM: MZM06B_OFSE ---*
  INCLUDE MM06BFSE_SEL_AKTIVIEREN .  " SEL_AKTIVIEREN

  INCLUDE MM06BFSE_SEL_ALLE .  " SEL_ALLE

  INCLUDE MM06BFSE_SEL_BLOCK .  " SEL_BLOCK

  INCLUDE zMM06BFSE_SEL_FCODE .  " SEL_FCODE

  INCLUDE MM06BFSE_SEL_INTERVALL .  " SEL_INTERVALL

  INCLUDE MM06BFSE_SEL_KENNZEICHNEN .  " SEL_KENNZEICHNEN

  INCLUDE MM06BFSE_SEL_LOESCHEN .  " SEL_LOESCHEN

  INCLUDE MM06BFSE_SEL_MERKEN .  " SEL_MERKEN

  INCLUDE MM06BFSE_SEL_PRUEFEN .  " SEL_PRUEFEN

  INCLUDE MM06BFSE_SEL_PRUEFEN_POERF .  " SEL_PRUEFEN_POERF
