*--- MAIN PROGRAM: MZM06B_OF0P ---*
  INCLUDE MM06BF0P_POS_ABBRECHEN .  " POS_ABBRECHEN

  INCLUDE MM06BF0P_POS_ENTLOESCHEN .  " POS_ENTLOESCHEN

  INCLUDE MM06BF0P_POS_EXIT .  " POS_EXIT

  INCLUDE MM06BF0P_POS_LOESCHEN .  " POS_LOESCHEN

  INCLUDE MM06BF0P_PRUEFEN_BSART_PSTYP .  " PRUEFEN_BSART_PSTYP

***END MM06bF01*********************************************************
