*****           Implementation of object type BUS2105              *****
INCLUDE <OBJECT>.
BEGIN_DATA OBJECT. " Do not change.. DATA is generated
* only private members may be inserted into structure private
DATA:
" begin of private,
"   to declare private attributes remove comments and
"   insert private attributes here ...
" end of private,
  BEGIN OF KEY,
      NUMBER LIKE EBAN-BANFN,
  END OF KEY.
END_DATA OBJECT. " Do not change.. DATA is generated
TABLES EBAN.


BEGIN_METHOD CHANGE CHANGING CONTAINER.
DATA:
      REQUISITIONITEMSOLD LIKE BAPIEBANV OCCURS 0,
      REQUISITIONITEMSNEW LIKE BAPIEBANV OCCURS 0,
      REQUISITIONACCOUNTOL LIKE BAPIEBKNV OCCURS 0,
      REQUISITIONACCOUNTNE LIKE BAPIEBKNV OCCURS 0,
      REQUISITIONTEXTOLD LIKE BAPIEBANTX OCCURS 0,
      REQUISITIONTEXTNEW LIKE BAPIEBANTX OCCURS 0,
      RETURN LIKE BAPIRETURN OCCURS 0.
SWC_GET_TABLE CONTAINER 'RequisitionItemsOld' REQUISITIONITEMSOLD.
SWC_GET_TABLE CONTAINER 'RequisitionItemsNew' REQUISITIONITEMSNEW.
SWC_GET_TABLE CONTAINER 'RequisitionAccountOl' REQUISITIONACCOUNTOL.
SWC_GET_TABLE CONTAINER 'RequisitionAccountNe' REQUISITIONACCOUNTNE.
SWC_GET_TABLE CONTAINER 'RequisitionTextOld' REQUISITIONTEXTOLD.
SWC_GET_TABLE CONTAINER 'RequisitionTextNew' REQUISITIONTEXTNEW.
SWC_GET_TABLE CONTAINER 'Return' RETURN.
CALL FUNCTION 'BAPI_REQUISITION_CHANGE'
  EXPORTING
    NUMBER                  = OBJECT-KEY-NUMBER
  TABLES
    RETURN                  = RETURN
    REQUISITION_TEXT_NEW    = REQUISITIONTEXTNEW
    REQUISITION_TEXT_OLD    = REQUISITIONTEXTOLD
    REQUISITION_ACCOUNT_NEW = REQUISITIONACCOUNTNE
    REQUISITION_ACCOUNT_OLD = REQUISITIONACCOUNTOL
    REQUISITION_ITEMS_NEW   = REQUISITIONITEMSNEW
    REQUISITION_ITEMS_OLD   = REQUISITIONITEMSOLD
  EXCEPTIONS
    OTHERS                  = 01.
CASE SY-SUBRC.
  WHEN 0.            " OK
  WHEN OTHERS.       " to be implemented
ENDCASE.
SWC_SET_TABLE CONTAINER 'RequisitionItemsOld' REQUISITIONITEMSOLD.
SWC_SET_TABLE CONTAINER 'RequisitionItemsNew' REQUISITIONITEMSNEW.
SWC_SET_TABLE CONTAINER 'RequisitionAccountOl' REQUISITIONACCOUNTOL.
SWC_SET_TABLE CONTAINER 'RequisitionAccountNe' REQUISITIONACCOUNTNE.
SWC_SET_TABLE CONTAINER 'RequisitionTextOld' REQUISITIONTEXTOLD.
SWC_SET_TABLE CONTAINER 'RequisitionTextNew' REQUISITIONTEXTNEW.
SWC_SET_TABLE CONTAINER 'Return' RETURN.
END_METHOD.


BEGIN_METHOD GETITEMSFORRELEASE CHANGING CONTAINER.
DATA:
      RELGROUP LIKE BAPIMMPARA-REL_GROUP,
      RELCODE LIKE BAPIMMPARA-REL_CODE,
      ITEMSFORRELEASE LIKE BAPIMMPARA-SELECTION,
      REQUISITIONITEMS LIKE BAPIEBANC OCCURS 0,
      RETURN LIKE BAPIRETURN OCCURS 0.
SWC_GET_ELEMENT CONTAINER 'RelGroup' RELGROUP.
SWC_GET_ELEMENT CONTAINER 'RelCode' RELCODE.
SWC_GET_ELEMENT CONTAINER 'ItemsForRelease' ITEMSFORRELEASE.
IF SY-SUBRC <> 0.
  MOVE 'X' TO ITEMSFORRELEASE.
ENDIF.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'RequisitionItems' REQUISITIONITEMS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'Return' RETURN.
" Code Remediation changes S4 2025_1_A Conversion **BEGIN OF CHANGE BY SAP_ABAP 06.06.2026  FOR ATC
CALL FUNCTION 'BAPI_REQUISITION_GETITEMSREL'"#EC CI_USAGE_OK[2438131]
" Code Remediation changes S4 2025_1_A Conversion * *END OF CHANGE BY SAP_ABAP 06.06.2026 FOR ATC
  EXPORTING
    ITEMS_FOR_RELEASE = ITEMSFORRELEASE
    REL_CODE          = RELCODE
    REL_GROUP         = RELGROUP
  TABLES
    REQUISITION_ITEMS = REQUISITIONITEMS
    RETURN            = RETURN
  EXCEPTIONS
    OTHERS            = 01.
CASE SY-SUBRC.
  WHEN 0.            " OK
  WHEN OTHERS.       " to be implemented
ENDCASE.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'RequisitionItems' REQUISITIONITEMS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'Return' RETURN.
END_METHOD.

BEGIN_METHOD DELETE CHANGING CONTAINER.
DATA:
      REQUISITIONITEMSTODE LIKE BAPIEBAND OCCURS 0,
      RETURN LIKE BAPIRETURN OCCURS 0.
SWC_GET_TABLE CONTAINER 'RequisitionItemsToDe' REQUISITIONITEMSTODE.
SWC_GET_TABLE CONTAINER 'Return' RETURN.
CALL FUNCTION 'BAPI_REQUISITION_DELETE'
  EXPORTING
    NUMBER                      = OBJECT-KEY-NUMBER
  TABLES
    REQUISITION_ITEMS_TO_DELETE = REQUISITIONITEMSTODE
    RETURN                      = RETURN
  EXCEPTIONS
    OTHERS                      = 01.
CASE SY-SUBRC.
  WHEN 0.            " OK
  WHEN OTHERS.       " to be implemented
ENDCASE.
SWC_SET_TABLE CONTAINER 'RequisitionItemsToDe' REQUISITIONITEMSTODE.
SWC_SET_TABLE CONTAINER 'Return' RETURN.
END_METHOD.

BEGIN_METHOD GETDETAIL CHANGING CONTAINER.
DATA:
      ACCOUNTASSIGNMENT LIKE BAPIMMPARA-SELECTION,
      ITEMTEXTS LIKE BAPIMMPARA-SELECTION,
      SERVICES LIKE BAPIMMPARA-SELECTION,
      SERVICETEXTS LIKE BAPIMMPARA-SELECTION,
      REQUISITIONITEMS LIKE BAPIEBAN OCCURS 0,
      REQUISITIONACCOUNTAS LIKE BAPIEBKN OCCURS 0,
      REQUISITIONTEXT LIKE BAPIEBANTX OCCURS 0,
      REQUISITIONLIMITS LIKE BAPIESUH OCCURS 0,
      REQUISITIONCONTRACTL LIKE BAPIESUC OCCURS 0,
      REQUISITIONSERVICES LIKE BAPIESLL OCCURS 0,
      REQUISITIONSRVTEXTS LIKE BAPIESLLTX OCCURS 0,
      REQUISITIONSRVACCASS LIKE BAPIESKL OCCURS 0,
      RETURN LIKE BAPIRETURN OCCURS 0.
SWC_GET_ELEMENT CONTAINER 'AccountAssignment' ACCOUNTASSIGNMENT.
IF SY-SUBRC <> 0.
  MOVE SPACE TO ACCOUNTASSIGNMENT.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'ItemTexts' ITEMTEXTS.
IF SY-SUBRC <> 0.
  MOVE SPACE TO ITEMTEXTS.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'Services' SERVICES.
IF SY-SUBRC <> 0.
  MOVE SPACE TO SERVICES.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'ServiceTexts' SERVICETEXTS.
IF SY-SUBRC <> 0.
  MOVE SPACE TO SERVICETEXTS.
ENDIF.

*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'RequisitionItems' REQUISITIONITEMS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'RequisitionAccountAs' REQUISITIONACCOUNTAS.
SWC_GET_TABLE CONTAINER 'RequisitionText' REQUISITIONTEXT.
SWC_GET_TABLE CONTAINER 'RequisitionLimits' REQUISITIONLIMITS.
SWC_GET_TABLE CONTAINER 'RequisitionContractL' REQUISITIONCONTRACTL.
SWC_GET_TABLE CONTAINER 'RequisitionServices' REQUISITIONSERVICES.
SWC_GET_TABLE CONTAINER 'RequisitionSrvTexts' REQUISITIONSRVTEXTS.
SWC_GET_TABLE CONTAINER 'RequisitionSrvAccass' REQUISITIONSRVACCASS.
SWC_GET_TABLE CONTAINER 'Return' RETURN.
" Code Remediation changes S4 2025_1_A Conversion **BEGIN OF CHANGE BY SAP_ABAP 06.06.2026  FOR ATC
CALL FUNCTION 'BAPI_REQUISITION_GETDETAIL'"#EC CI_USAGE_OK[2438131]
" Code Remediation changes S4 2025_1_A Conversion * *END OF CHANGE BY SAP_ABAP 06.06.2026 FOR ATC
  EXPORTING
    SERVICES                       = SERVICES
    SERVICE_TEXTS                  = SERVICETEXTS
    ITEM_TEXTS                     = ITEMTEXTS
    ACCOUNT_ASSIGNMENT             = ACCOUNTASSIGNMENT
    NUMBER                         = OBJECT-KEY-NUMBER
  TABLES
    REQUISITION_CONTRACT_LIMITS    = REQUISITIONCONTRACTL
    REQUISITION_SERVICES           = REQUISITIONSERVICES
    REQUISITION_SERVICES_TEXTS     = REQUISITIONSRVTEXTS
    REQUISITION_SRV_ACCASS_VALUES  = REQUISITIONSRVACCASS
    RETURN                         = RETURN
    REQUISITION_LIMITS             = REQUISITIONLIMITS
    REQUISITION_TEXT               = REQUISITIONTEXT
    REQUISITION_ACCOUNT_ASSIGNMENT = REQUISITIONACCOUNTAS
    REQUISITION_ITEMS              = REQUISITIONITEMS
  EXCEPTIONS
    OTHERS                         = 01.
CASE SY-SUBRC.
  WHEN 0.            " OK
  WHEN OTHERS.       " to be implemented
ENDCASE.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'RequisitionItems' REQUISITIONITEMS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'RequisitionAccountAs' REQUISITIONACCOUNTAS.
SWC_SET_TABLE CONTAINER 'RequisitionText' REQUISITIONTEXT.
SWC_SET_TABLE CONTAINER 'RequisitionLimits' REQUISITIONLIMITS.
SWC_SET_TABLE CONTAINER 'RequisitionContractL' REQUISITIONCONTRACTL.
SWC_SET_TABLE CONTAINER 'RequisitionServices' REQUISITIONSERVICES.
SWC_SET_TABLE CONTAINER 'RequisitionSrvTexts' REQUISITIONSRVTEXTS.
SWC_SET_TABLE CONTAINER 'RequisitionSrvAccass' REQUISITIONSRVACCASS.
SWC_SET_TABLE CONTAINER 'Return' RETURN.
END_METHOD.

BEGIN_METHOD GETRELEASEINFO CHANGING CONTAINER.
DATA:
      ITEM LIKE BAPIRLGNRQ-PREQ_ITEM,
      RELCODE LIKE BAPIRLGNRQ-REL_CODE,
      GENERALRELEASEINFO LIKE BAPIRLGNRQ OCCURS 0,
      RELEASEPREREQUISITES LIKE BAPIRLCORQ OCCURS 0,
      RELEASEALREADYPOSTED LIKE BAPIRLCORQ OCCURS 0,
      RELEASEFINAL LIKE BAPIRLCORQ OCCURS 0,
      RETURN LIKE BAPIRETURN OCCURS 0.
SWC_GET_ELEMENT CONTAINER 'Item' ITEM.
SWC_GET_ELEMENT CONTAINER 'RelCode' RELCODE.
SWC_GET_TABLE CONTAINER 'GeneralReleaseInfo' GENERALRELEASEINFO.
SWC_GET_TABLE CONTAINER 'ReleasePrerequisites' RELEASEPREREQUISITES.
SWC_GET_TABLE CONTAINER 'ReleaseAlreadyPosted' RELEASEALREADYPOSTED.
SWC_GET_TABLE CONTAINER 'ReleaseFinal' RELEASEFINAL.
SWC_GET_TABLE CONTAINER 'Return' RETURN.
CALL FUNCTION 'BAPI_REQUISITION_GETRELINFO'
  EXPORTING
    REL_CODE               = RELCODE
    ITEM                   = ITEM
    NUMBER                 = OBJECT-KEY-NUMBER
  TABLES
    RETURN                 = RETURN
    RELEASE_FINAL          = RELEASEFINAL
    RELEASE_ALREADY_POSTED = RELEASEALREADYPOSTED
    RELEASE_PREREQUISITES  = RELEASEPREREQUISITES
    GENERAL_RELEASE_INFO   = GENERALRELEASEINFO
  EXCEPTIONS
    OTHERS                 = 01.
CASE SY-SUBRC.
  WHEN 0.            " OK
  WHEN OTHERS.       " to be implemented
ENDCASE.
SWC_SET_TABLE CONTAINER 'GeneralReleaseInfo' GENERALRELEASEINFO.
SWC_SET_TABLE CONTAINER 'ReleasePrerequisites' RELEASEPREREQUISITES.
SWC_SET_TABLE CONTAINER 'ReleaseAlreadyPosted' RELEASEALREADYPOSTED.
SWC_SET_TABLE CONTAINER 'ReleaseFinal' RELEASEFINAL.
SWC_SET_TABLE CONTAINER 'Return' RETURN.
END_METHOD.

BEGIN_METHOD DISPLAY CHANGING CONTAINER.
CALL FUNCTION 'MMPUR_REQUISITION_DISPLAY'
  EXPORTING
    IM_BANFN = OBJECT-KEY-NUMBER
  EXCEPTIONS
    OTHERS   = 1.
IF SY-SUBRC <> 0.
  MESSAGE ID SY-MSGID TYPE 'S' NUMBER SY-MSGNO
          WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
END_METHOD.

BEGIN_METHOD EXISTENCECHECK CHANGING CONTAINER.
DATA: LV_BANFN LIKE OBJECT-KEY-NUMBER.

SELECT BANFN FROM EBAN INTO LV_BANFN
                       WHERE BANFN EQ OBJECT-KEY-NUMBER.
ENDSELECT.
IF SY-SUBRC NE 0.                                           "154883
  EXIT_OBJECT_NOT_FOUND.                                    "154883
ENDIF.                                                      "154883
END_METHOD.

BEGIN_METHOD SINGLERELEASE CHANGING CONTAINER.
DATA: PURCHASEREQUISITION LIKE EBAN-BANFN,
      RELEASECODE LIKE RM06B-FRGAB,
      CALL_UPDKZ.

SWC_GET_ELEMENT CONTAINER 'ReleaseCode' RELEASECODE.
PURCHASEREQUISITION = OBJECT-KEY-NUMBER.

CALL FUNCTION 'ME_RELEASE_REQUISITION'
  EXPORTING
    IM_BANFN = PURCHASEREQUISITION
    IM_FRGCO = RELEASECODE
    IM_WF    = 'X'
  IMPORTING
    EX_UPDKZ = CALL_UPDKZ
  EXCEPTIONS
    OTHERS   = 0.

IF CALL_UPDKZ NE SPACE.
  IF CALL_UPDKZ EQ 'N'.
    CLEAR CALL_UPDKZ.
  ENDIF.
  SWC_SET_ELEMENT CONTAINER RESULT CALL_UPDKZ.
ELSE.
  EXIT_CANCELLED.
ENDIF.

END_METHOD.

BEGIN_METHOD INFORELEASERESET CHANGING CONTAINER.
DATA:
   RELEASECODE LIKE RM06B-FRGAB.
SWC_GET_ELEMENT CONTAINER 'ReleaseCode' RELEASECODE.

END_METHOD.

BEGIN_METHOD INFORELEASEREJECTED CHANGING CONTAINER.
CALL FUNCTION 'MMPUR_REQUISITION_DISPLAY'
  EXPORTING
    IM_BANFN  = OBJECT-KEY-NUMBER
    IM_CHANGE = 'X'
  EXCEPTIONS
    OTHERS    = 1.
IF SY-SUBRC <> 0.
  MESSAGE ID SY-MSGID TYPE 'S' NUMBER SY-MSGNO
          WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
END_METHOD.

BEGIN_METHOD INFORELEASEEFFECTED CHANGING CONTAINER.

DATA:
    RELEASECODE LIKE RM06B-FRGAB.
SWC_GET_ELEMENT CONTAINER 'ReleaseCode' RELEASECODE.

END_METHOD.

BEGIN_METHOD RELEASE CHANGING CONTAINER.
DATA:
      RELCODE LIKE BAPIMMPARA-REL_CODE,
      RELSTATUSNEW LIKE BAPIMMPARA-REL_STATUS,
      RELINDICATORNEW LIKE BAPIMMPARA-REL_IND,
      RETURN LIKE BAPIRETURN OCCURS 0,
      NOCOMMITWORK TYPE BAPIFLAG-BAPIFLAG.
SWC_GET_ELEMENT CONTAINER 'RelCode' RELCODE.
SWC_GET_TABLE CONTAINER 'Return' RETURN.
SWC_GET_ELEMENT CONTAINER 'NoCommitWork' NOCOMMITWORK.
CALL FUNCTION 'BAPI_REQUISITION_RELEASE_GEN'
  EXPORTING
    NUMBER            = OBJECT-KEY-NUMBER
    REL_CODE          = RELCODE
    NO_COMMIT_WORK    = NOCOMMITWORK
  IMPORTING
    REL_INDICATOR_NEW = RELINDICATORNEW
    REL_STATUS_NEW    = RELSTATUSNEW
  TABLES
    RETURN            = RETURN
  EXCEPTIONS
    OTHERS            = 01.
CASE SY-SUBRC.
  WHEN 0.            " OK
  WHEN OTHERS.       " to be implemented
ENDCASE.
SWC_SET_ELEMENT CONTAINER 'RelStatusNew' RELSTATUSNEW.
SWC_SET_ELEMENT CONTAINER 'RelIndicatorNew' RELINDICATORNEW.
SWC_SET_TABLE CONTAINER 'Return' RETURN.
END_METHOD.

BEGIN_METHOD RESETRELEASE CHANGING CONTAINER.
DATA:
      RELCODE LIKE BAPIMMPARA-REL_CODE,
      RELSTATUSNEW LIKE BAPIMMPARA-REL_STATUS,
      RELINDICATORNEW LIKE BAPIMMPARA-REL_IND,
      RETURN LIKE BAPIRETURN OCCURS 0.
SWC_GET_ELEMENT CONTAINER 'RelCode' RELCODE.
SWC_GET_TABLE CONTAINER 'Return' RETURN.
CALL FUNCTION 'BAPI_REQUISITION_RESET_REL_GEN'
  EXPORTING
    NUMBER            = OBJECT-KEY-NUMBER
    REL_CODE          = RELCODE
  IMPORTING
    REL_INDICATOR_NEW = RELINDICATORNEW
    REL_STATUS_NEW    = RELSTATUSNEW
  TABLES
    RETURN            = RETURN
  EXCEPTIONS
    OTHERS            = 01.
CASE SY-SUBRC.
  WHEN 0.            " OK
  WHEN OTHERS.       " to be implemented
ENDCASE.
SWC_SET_ELEMENT CONTAINER 'RelStatusNew' RELSTATUSNEW.
SWC_SET_ELEMENT CONTAINER 'RelIndicatorNew' RELINDICATORNEW.
SWC_SET_TABLE CONTAINER 'Return' RETURN.
END_METHOD.


BEGIN_METHOD EDIT CHANGING CONTAINER.
CALL FUNCTION 'MMPUR_REQUISITION_DISPLAY'
  EXPORTING
    IM_BANFN  = OBJECT-KEY-NUMBER
    IM_CHANGE = 'X'
  EXCEPTIONS
    OTHERS    = 1.
IF SY-SUBRC <> 0.
  MESSAGE ID SY-MSGID TYPE 'S' NUMBER SY-MSGNO
          WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
END_METHOD.

BEGIN_METHOD CREATEFROMDATA CHANGING CONTAINER.
DATA:
      REQUISITIONITEMS LIKE BAPIEBANC OCCURS 0,
      REQUISITIONACCOUNTAS LIKE BAPIEBKN OCCURS 0,
      REQUISITIONITEMTEXT LIKE BAPIEBANTX OCCURS 0,
      REQUISITIONLIMITS LIKE BAPIESUHC OCCURS 0,
      REQUISITIONCONTRACTL LIKE BAPIESUCC OCCURS 0,
      REQUISITIONSERVICES LIKE BAPIESLLC OCCURS 0,
      REQUISITIONSRVTEXT LIKE BAPIESLLTX OCCURS 0,
      REQUISITIONSRVACCASS LIKE BAPIESKLC OCCURS 0,
      RETURN LIKE BAPIRETURN OCCURS 0,
      EXTENSIONIN LIKE BAPIPAREX OCCURS 0,
      SKIPITEMSWITHERROR LIKE BAPIMMPARA-SELECTION.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'RequisitionItems' REQUISITIONITEMS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'RequisitionAccountAs' REQUISITIONACCOUNTAS.
SWC_GET_TABLE CONTAINER 'RequisitionItemText' REQUISITIONITEMTEXT.
SWC_GET_TABLE CONTAINER 'RequisitionLimits' REQUISITIONLIMITS.
SWC_GET_TABLE CONTAINER 'RequisitionContractL' REQUISITIONCONTRACTL.
SWC_GET_TABLE CONTAINER 'RequisitionServices' REQUISITIONSERVICES.
SWC_GET_TABLE CONTAINER 'RequisitionSrvText' REQUISITIONSRVTEXT.
SWC_GET_TABLE CONTAINER 'RequisitionSrvAccass' REQUISITIONSRVACCASS.
SWC_GET_TABLE CONTAINER 'ExtensionIn' EXTENSIONIN.
SWC_GET_ELEMENT CONTAINER 'SkipItemsWithError' SKIPITEMSWITHERROR.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
CALL FUNCTION 'BAPI_REQUISITION_CREATE'  "#EC CI_USAGE_OK[1803189]
"#EC CI_USAGE_OK[2438131]
  EXPORTING
    SKIP_ITEMS_WITH_ERROR          = SKIPITEMSWITHERROR
  IMPORTING
    NUMBER                         = OBJECT-KEY-NUMBER
  TABLES
    REQUISITION_SERVICES           = REQUISITIONSERVICES
    REQUISITION_SRV_ACCASS_VALUES  = REQUISITIONSRVACCASS
    RETURN                         = RETURN
    REQUISITION_SERVICES_TEXT      = REQUISITIONSRVTEXT
    EXTENSIONIN                    = EXTENSIONIN
    REQUISITION_ITEMS              = REQUISITIONITEMS
    REQUISITION_ACCOUNT_ASSIGNMENT = REQUISITIONACCOUNTAS
    REQUISITION_ITEM_TEXT          = REQUISITIONITEMTEXT
    REQUISITION_LIMITS             = REQUISITIONLIMITS
    REQUISITION_CONTRACT_LIMITS    = REQUISITIONCONTRACTL
  EXCEPTIONS
    OTHERS                         = 01.
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
CASE SY-SUBRC.
  WHEN 0.            " OK
  WHEN OTHERS.       " to be implemented
ENDCASE.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'RequisitionItems' REQUISITIONITEMS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'RequisitionAccountAs' REQUISITIONACCOUNTAS.
SWC_SET_TABLE CONTAINER 'RequisitionItemText' REQUISITIONITEMTEXT.
SWC_SET_TABLE CONTAINER 'RequisitionLimits' REQUISITIONLIMITS.
SWC_SET_TABLE CONTAINER 'RequisitionContractL' REQUISITIONCONTRACTL.
SWC_SET_TABLE CONTAINER 'RequisitionServices' REQUISITIONSERVICES.
SWC_SET_TABLE CONTAINER 'RequisitionSrvAccass' REQUISITIONSRVACCASS.
SWC_SET_TABLE CONTAINER 'Return' RETURN.
END_METHOD.

BEGIN_METHOD EDITASYNC CHANGING CONTAINER.
CALL FUNCTION 'MMPUR_REQUISITION_DISPLAY'
  EXPORTING
    IM_BANFN  = OBJECT-KEY-NUMBER
    IM_CHANGE = 'X'
  EXCEPTIONS
    OTHERS    = 1.
IF SY-SUBRC <> 0.
  MESSAGE ID SY-MSGID TYPE 'S' NUMBER SY-MSGNO
          WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
END_METHOD.

BEGIN_METHOD CREATEFROMDATA1 CHANGING CONTAINER.
DATA:
      PRHEADER LIKE BAPIMEREQHEADER,
      PRHEADERX LIKE BAPIMEREQHEADERX,
      TESTRUN TYPE BAPIFLAG-BAPIFLAG,
      PRNUMBER TYPE BAPIMEREQHEADER-PREQ_NO,
      PRHEADEREXP LIKE BAPIMEREQHEADER,
      RETURN LIKE BAPIRET2 OCCURS 0,
      PRITEM LIKE BAPIMEREQITEMIMP OCCURS 0,
      PRITEMX LIKE BAPIMEREQITEMX OCCURS 0,
      PRITEMEXP LIKE BAPIMEREQITEM OCCURS 0,
      PRITEMSOURCE LIKE BAPIMEREQSOURCE OCCURS 0,
      PRACCOUNT LIKE BAPIMEREQACCOUNT OCCURS 0,
      PRACCOUNTPROITSEGMENT LIKE BAPIMEREQACCOUNTPROFITSEG OCCURS 0,
      PRACCOUNTX LIKE BAPIMEREQACCOUNTX OCCURS 0,
      PRADDRDELIVERY LIKE BAPIMERQADDRDELIVERY OCCURS 0,
      PRITEMTEXT LIKE BAPIMEREQITEMTEXT OCCURS 0,
      PRHEADERTEXT LIKE BAPIMEREQHEADTEXT OCCURS 0,
      PRVERSION LIKE BAPIMEREQDCM OCCURS 0,
      PRVERSIONX LIKE BAPIMEREQDCMX OCCURS 0,
      EXTENSIONIN LIKE BAPIPAREX OCCURS 0,
      EXTENSIONOUT LIKE BAPIPAREX OCCURS 0,
      PRCOMPONENTS LIKE BAPIMEREQCOMPONENT OCCURS 0,
      PRCOMPONENTSX LIKE BAPIMEREQCOMPONENTX OCCURS 0,
      SERIALNUMBER LIKE BAPIMEREQSERIALNO OCCURS 0,
      SERIALNUMBERX LIKE BAPIMEREQSERIALNOX OCCURS 0,
      ALLVERSIONS LIKE BAPIMEDCM_ALLVERSIONS OCCURS 0,
      SERVICEOUTLINE TYPE TABLE OF BAPI_SRV_OUTLINE,
      SERVICEOUTLINEX TYPE TABLE OF BAPI_SRV_OUTLINEX,
      SERVICELINES TYPE TABLE OF BAPI_SRV_SERVICE_LINE,
      SERVICELINESX TYPE TABLE OF BAPI_SRV_SERVICE_LINEX,
      SERVICELIMIT TYPE TABLE OF BAPI_SRV_LIMIT_DATA,
      SERVICELIMITX TYPE TABLE OF BAPI_SRV_LIMIT_DATAX,
      SERVICECONTRACTLIMITS TYPE TABLE OF BAPI_SRV_CONTRACT_LIMITS,
      SERVICECONTRACTLIMITSX TYPE TABLE OF BAPI_SRV_CONTRACT_LIMITSX,
      SERVICEACCOUNT TYPE TABLE OF BAPI_SRV_ACC_DATA,
      SERVICEACCOUNTX TYPE TABLE OF BAPI_SRV_ACC_DATAX,
      SERVICELONGTEXTS TYPE TABLE OF BAPI_SRV_LONGTEXTS.
SWC_GET_ELEMENT CONTAINER 'PrHeader' PRHEADER.
SWC_GET_ELEMENT CONTAINER 'PrHeaderX' PRHEADERX.
SWC_GET_ELEMENT CONTAINER 'PrVersion' PRVERSION.
SWC_GET_ELEMENT CONTAINER 'PrVersionX' PRVERSIONX.
SWC_GET_ELEMENT CONTAINER 'Testrun' TESTRUN.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'PrItem' PRITEM.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'PrItemX' PRITEMX.
SWC_GET_TABLE CONTAINER 'PrAccount' PRACCOUNT.
SWC_GET_TABLE CONTAINER 'PrAccountProitSegment' PRACCOUNTPROITSEGMENT.
SWC_GET_TABLE CONTAINER 'PrAccountX' PRACCOUNTX.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'PrComponents' PRCOMPONENTS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'PrComponentsX' PRCOMPONENTSX.
SWC_GET_TABLE CONTAINER 'PRSerialNumber' SERIALNUMBER.
SWC_GET_TABLE CONTAINER 'PRSerialNumberX' SERIALNUMBERX.
SWC_GET_TABLE CONTAINER 'PrAddrDelivery' PRADDRDELIVERY.
SWC_GET_TABLE CONTAINER 'PrItemText' PRITEMTEXT.
SWC_GET_TABLE CONTAINER 'PrHeaderText' PRHEADERTEXT.
SWC_GET_TABLE CONTAINER 'Extensionin' EXTENSIONIN.
SWC_GET_TABLE CONTAINER 'Allversions' ALLVERSIONS.
SWC_GET_TABLE CONTAINER 'ServiceOutline' SERVICEOUTLINE.
SWC_GET_TABLE CONTAINER 'ServiceOutlineX' SERVICEOUTLINEX.
SWC_GET_TABLE CONTAINER 'ServiceLines' SERVICELINES.
SWC_GET_TABLE CONTAINER 'ServiceLinesX' SERVICELINESX.
SWC_GET_TABLE CONTAINER 'ServiceLimit'  SERVICELIMIT.
SWC_GET_TABLE CONTAINER 'ServiceLimitX' SERVICELIMITX.
SWC_GET_TABLE CONTAINER 'ServiceContractLimits' SERVICECONTRACTLIMITS.
SWC_GET_TABLE CONTAINER 'ServiceContractLimitsX' SERVICECONTRACTLIMITSX.
SWC_GET_TABLE CONTAINER 'ServiceAccount' SERVICEACCOUNT.
SWC_GET_TABLE CONTAINER 'ServiceAccountX' SERVICEACCOUNTX.
SWC_GET_TABLE CONTAINER 'ServiceLongtexts' SERVICELONGTEXTS.
" Code Remediation changes S4 2025_1_A Conversion **BEGIN OF CHANGE BY SAP_ABAP 06.06.2026  FOR ATC
CALL FUNCTION 'BAPI_PR_CREATE'"#EC CI_USAGE_OK[2438131]
" Code Remediation changes S4 2025_1_A Conversion * *END OF CHANGE BY SAP_ABAP 06.06.2026 FOR ATC
  EXPORTING
    PRHEADER               = PRHEADER
    PRHEADERX              = PRHEADERX
    TESTRUN                = TESTRUN
  IMPORTING
    NUMBER                 = OBJECT-KEY-NUMBER
    PRHEADEREXP            = PRHEADEREXP
  TABLES
    PRHEADERTEXT           = PRHEADERTEXT
    EXTENSIONIN            = EXTENSIONIN
    EXTENSIONOUT           = EXTENSIONOUT
    ALLVERSIONS            = ALLVERSIONS
    PRITEMTEXT             = PRITEMTEXT
    PRADDRDELIVERY         = PRADDRDELIVERY
    PRACCOUNTX             = PRACCOUNTX
    PRACCOUNTPROITSEGMENT  = PRACCOUNTPROITSEGMENT
    PRACCOUNT              = PRACCOUNT
    SERIALNUMBER           = SERIALNUMBER
    SERIALNUMBERX          = SERIALNUMBERX
    PRCOMPONENTS           = PRCOMPONENTS
    PRCOMPONENTSX          = PRCOMPONENTSX
    PRITEMSOURCE           = PRITEMSOURCE
    PRITEMEXP              = PRITEMEXP
    PRITEMX                = PRITEMX
    PRITEM                 = PRITEM
    PRVERSION              = PRVERSION
    PRVERSIONX             = PRVERSIONX
    RETURN                 = RETURN
    SERVICEOUTLINE         = SERVICEOUTLINE
    SERVICEOUTLINEX        = SERVICEOUTLINEX
    SERVICELINES           = SERVICELINES
    SERVICELINESX          = SERVICELINESX
    SERVICELIMIT           = SERVICELIMIT
    SERVICELIMITX          = SERVICELIMITX
    SERVICECONTRACTLIMITS  = SERVICECONTRACTLIMITS
    SERVICECONTRACTLIMITSX = SERVICECONTRACTLIMITSX
    SERVICEACCOUNT         = SERVICEACCOUNT
    SERVICEACCOUNTX        = SERVICEACCOUNTX
    SERVICELONGTEXTS       = SERVICELONGTEXTS
  EXCEPTIONS
    OTHERS                 = 01.
CASE SY-SUBRC.
  WHEN 0.            " OK
  WHEN OTHERS.       " to be implemented
ENDCASE.
SWC_SET_ELEMENT CONTAINER 'Number' PRNUMBER.
SWC_SET_ELEMENT CONTAINER 'PrHeaderExp' PRHEADEREXP.
SWC_SET_TABLE CONTAINER 'Return' RETURN.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'PrItemExp' PRITEMEXP.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'PrItemSource' PRITEMSOURCE.
SWC_SET_TABLE CONTAINER 'PrAccount' PRACCOUNT.
SWC_SET_TABLE CONTAINER 'PrAccountProitSegment' PRACCOUNTPROITSEGMENT.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'PrComponents' PRCOMPONENTS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'PRSerialNumber' SERIALNUMBER.
SWC_SET_TABLE CONTAINER 'PrAddrDelivery' PRADDRDELIVERY.
SWC_SET_TABLE CONTAINER 'PrItemText' PRITEMTEXT.
SWC_SET_TABLE CONTAINER 'PrHeaderText' PRHEADERTEXT.
SWC_SET_TABLE CONTAINER 'Extensionin' EXTENSIONIN.
SWC_SET_TABLE CONTAINER 'Extensionout' EXTENSIONOUT.
SWC_SET_TABLE CONTAINER 'Allversions' ALLVERSIONS.
SWC_SET_TABLE CONTAINER 'ServiceOutline' SERVICEOUTLINE.
SWC_SET_TABLE CONTAINER 'ServiceLines' SERVICELINES.
SWC_SET_TABLE CONTAINER 'ServiceLimit'  SERVICELIMIT.
SWC_SET_TABLE CONTAINER 'ServiceContractLimits' SERVICECONTRACTLIMITS.
SWC_SET_TABLE CONTAINER 'ServiceAccount' SERVICEACCOUNT.
SWC_SET_TABLE CONTAINER 'ServiceLongtexts' SERVICELONGTEXTS.
END_METHOD.

BEGIN_METHOD CHANGE1 CHANGING CONTAINER.
DATA:
      PRHEADER LIKE BAPIMEREQHEADER,
      PRHEADERX LIKE BAPIMEREQHEADERX,
      PRHEADEREXP LIKE BAPIMEREQHEADER,
      TESTRUN TYPE BAPIFLAG-BAPIFLAG,
      RETURN LIKE BAPIRET2 OCCURS 0,
      PRITEM LIKE BAPIMEREQITEMIMP OCCURS 0,
      PRITEMX LIKE BAPIMEREQITEMX OCCURS 0,
      PRITEMEXP LIKE BAPIMEREQITEM OCCURS 0,
      PRITEMSOURCE LIKE BAPIMEREQSOURCE OCCURS 0,
      PRACCOUNT LIKE BAPIMEREQACCOUNT OCCURS 0,
      PRACCOUNTPROITSEGMENT LIKE BAPIMEREQACCOUNTPROFITSEG OCCURS 0,
      PRACCOUNTX LIKE BAPIMEREQACCOUNTX OCCURS 0,
      PRCOMPONENTS LIKE BAPIMEREQCOMPONENT OCCURS 0,
      PRCOMPONENTSX LIKE BAPIMEREQCOMPONENTX OCCURS 0,
      SERIALNUMBER LIKE BAPIMEREQSERIALNO OCCURS 0,
      SERIALNUMBERX LIKE BAPIMEREQSERIALNOX OCCURS 0,
      PRADDRDELIVERY LIKE BAPIMERQADDRDELIVERY OCCURS 0,
      PRITEMTEXT LIKE BAPIMEREQITEMTEXT OCCURS 0,
      PRHEADERTEXT LIKE BAPIMEREQHEADTEXT OCCURS 0,
      EXTENSIONIN LIKE BAPIPAREX OCCURS 0,
      EXTENSIONOUT LIKE BAPIPAREX OCCURS 0,
      PRVERSION LIKE BAPIMEREQDCM OCCURS 0,
      PRVERSIONX LIKE BAPIMEREQDCMX OCCURS 0,
      ALLVERSIONS LIKE BAPIMEDCM_ALLVERSIONS OCCURS 0,
      SERVICEOUTLINE TYPE TABLE OF BAPI_SRV_OUTLINE,
      SERVICEOUTLINEX TYPE TABLE OF BAPI_SRV_OUTLINEX,
      SERVICELINES TYPE TABLE OF BAPI_SRV_SERVICE_LINE,
      SERVICELINESX TYPE TABLE OF BAPI_SRV_SERVICE_LINEX,
      SERVICELIMIT TYPE TABLE OF BAPI_SRV_LIMIT_DATA,
      SERVICELIMITX TYPE TABLE OF BAPI_SRV_LIMIT_DATAX,
      SERVICECONTRACTLIMITS TYPE TABLE OF BAPI_SRV_CONTRACT_LIMITS,
      SERVICECONTRACTLIMITSX TYPE TABLE OF BAPI_SRV_CONTRACT_LIMITSX,
      SERVICEACCOUNT TYPE TABLE OF BAPI_SRV_ACC_DATA,
      SERVICEACCOUNTX TYPE TABLE OF BAPI_SRV_ACC_DATAX,
      SERVICELONGTEXTS TYPE TABLE OF BAPI_SRV_LONGTEXTS.
SWC_GET_ELEMENT CONTAINER 'PrHeader' PRHEADER.
SWC_GET_ELEMENT CONTAINER 'PrHeaderX' PRHEADERX.
SWC_GET_ELEMENT CONTAINER 'PrVersion' PRVERSION.
SWC_GET_ELEMENT CONTAINER 'PrVersionX' PRVERSIONX.
SWC_GET_ELEMENT CONTAINER 'Testrun' TESTRUN.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'PrItem' PRITEM.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'PrItemX' PRITEMX.
SWC_GET_TABLE CONTAINER 'PrAccount' PRACCOUNT.
SWC_GET_TABLE CONTAINER 'PrAccountProitSegment' PRACCOUNTPROITSEGMENT.
SWC_GET_TABLE CONTAINER 'PrAccountX' PRACCOUNTX.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'PrComponents' PRCOMPONENTS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'PrComponentsX' PRCOMPONENTSX.
SWC_GET_TABLE CONTAINER 'PRSerialNumber' SERIALNUMBER.
SWC_GET_TABLE CONTAINER 'PRSerialNumberX' SERIALNUMBERX.
SWC_GET_TABLE CONTAINER 'PrAddrDelivery' PRADDRDELIVERY.
SWC_GET_TABLE CONTAINER 'PrItemText' PRITEMTEXT.
SWC_GET_TABLE CONTAINER 'PrHeaderText' PRHEADERTEXT.
SWC_GET_TABLE CONTAINER 'Extensionin' EXTENSIONIN.
SWC_GET_TABLE CONTAINER 'AllVersions' ALLVERSIONS.
SWC_GET_TABLE CONTAINER 'ServiceOutline' SERVICEOUTLINE.
SWC_GET_TABLE CONTAINER 'ServiceOutlineX' SERVICEOUTLINEX.
SWC_GET_TABLE CONTAINER 'ServiceLines' SERVICELINES.
SWC_GET_TABLE CONTAINER 'ServiceLinesX' SERVICELINESX.
SWC_GET_TABLE CONTAINER 'ServiceLimit'  SERVICELIMIT.
SWC_GET_TABLE CONTAINER 'ServiceLimitX' SERVICELIMITX.
SWC_GET_TABLE CONTAINER 'ServiceContractLimits' SERVICECONTRACTLIMITS.
SWC_GET_TABLE CONTAINER 'ServiceContractLimitsX' SERVICECONTRACTLIMITSX.
SWC_GET_TABLE CONTAINER 'ServiceAccount' SERVICEACCOUNT.
SWC_GET_TABLE CONTAINER 'ServiceAccountX' SERVICEACCOUNTX.
SWC_GET_TABLE CONTAINER 'ServiceLongtexts' SERVICELONGTEXTS.
" Code Remediation changes S4 2025_1_A Conversion **BEGIN OF CHANGE BY SAP_ABAP 06.06.2026  FOR ATC
CALL FUNCTION 'BAPI_PR_CHANGE'"#EC CI_USAGE_OK[2438131]
" Code Remediation changes S4 2025_1_A Conversion * *END OF CHANGE BY SAP_ABAP 06.06.2026 FOR ATC
  EXPORTING
    NUMBER                 = OBJECT-KEY-NUMBER
    PRHEADER               = PRHEADER
    PRHEADERX              = PRHEADERX
    TESTRUN                = TESTRUN
  IMPORTING
    PRHEADEREXP            = PRHEADEREXP
  TABLES
    PRHEADERTEXT           = PRHEADERTEXT
    EXTENSIONIN            = EXTENSIONIN
    EXTENSIONOUT           = EXTENSIONOUT
    ALLVERSIONS            = ALLVERSIONS
    PRITEMTEXT             = PRITEMTEXT
    PRADDRDELIVERY         = PRADDRDELIVERY
    PRACCOUNTX             = PRACCOUNTX
    PRACCOUNTPROITSEGMENT  = PRACCOUNTPROITSEGMENT
    PRACCOUNT              = PRACCOUNT
    SERIALNUMBER           = SERIALNUMBER
    SERIALNUMBERX          = SERIALNUMBERX
    PRCOMPONENTS           = PRCOMPONENTS
    PRCOMPONENTSX          = PRCOMPONENTSX
    PRITEMSOURCE           = PRITEMSOURCE
    PRITEMEXP              = PRITEMEXP
    PRITEMX                = PRITEMX
    PRITEM                 = PRITEM
    PRVERSION              = PRVERSION
    PRVERSIONX             = PRVERSIONX
    RETURN                 = RETURN
    SERVICEOUTLINE         = SERVICEOUTLINE
    SERVICEOUTLINEX        = SERVICEOUTLINEX
    SERVICELINES           = SERVICELINES
    SERVICELINESX          = SERVICELINESX
    SERVICELIMIT           = SERVICELIMIT
    SERVICELIMITX          = SERVICELIMITX
    SERVICECONTRACTLIMITS  = SERVICECONTRACTLIMITS
    SERVICECONTRACTLIMITSX = SERVICECONTRACTLIMITSX
    SERVICEACCOUNT         = SERVICEACCOUNT
    SERVICEACCOUNTX        = SERVICEACCOUNTX
    SERVICELONGTEXTS       = SERVICELONGTEXTS
  EXCEPTIONS
    OTHERS                 = 01.
CASE SY-SUBRC.
  WHEN 0.            " OK
  WHEN OTHERS.       " to be implemented
ENDCASE.
SWC_SET_ELEMENT CONTAINER 'PrHeaderExp' PRHEADEREXP.
SWC_SET_TABLE CONTAINER 'Return' RETURN.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'PrItemExp' PRITEMEXP.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'PrItemSource' PRITEMSOURCE.
SWC_SET_TABLE CONTAINER 'PrAccount' PRACCOUNT.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'PrComponents' PRCOMPONENTS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'PRSerialNumber' SERIALNUMBER.
SWC_SET_TABLE CONTAINER 'PrAddrDelivery' PRADDRDELIVERY.
SWC_SET_TABLE CONTAINER 'PrItemText' PRITEMTEXT.
SWC_SET_TABLE CONTAINER 'PrHeaderText' PRHEADERTEXT.
SWC_SET_TABLE CONTAINER 'Extensionout' EXTENSIONOUT.
SWC_SET_TABLE CONTAINER 'AllVersions' ALLVERSIONS.
SWC_SET_TABLE CONTAINER 'ServiceOutline' SERVICEOUTLINE.
SWC_SET_TABLE CONTAINER 'ServiceLines' SERVICELINES.
SWC_SET_TABLE CONTAINER 'ServiceLimit'  SERVICELIMIT.
SWC_SET_TABLE CONTAINER 'ServiceContractLimits' SERVICECONTRACTLIMITS.
SWC_SET_TABLE CONTAINER 'ServiceAccount' SERVICEACCOUNT.
SWC_SET_TABLE CONTAINER 'ServiceLongtexts' SERVICELONGTEXTS.
END_METHOD.

BEGIN_METHOD GETDETAIL1 CHANGING CONTAINER.
DATA:
      ACCOUNTASSIGNMENT TYPE BAPIMMPARA-SELECTION,
      ITEMTEXT TYPE BAPIMMPARA-SELECTION,
      HEADERTEXT TYPE BAPIMMPARA-SELECTION,
      VERSION TYPE BAPIMMPARA-SELECTION,
      DELIVERYADDRESS TYPE BAPIMMPARA-SELECTION,
      COMPONENTS TYPE BAPIMMPARA-SELECTION,
      SERIAL_NUMBERS TYPE BAPIMMPARA-SELECTION,
      SERVICES TYPE BAPIMMPARA-SELECTION,
      RETURN LIKE BAPIRET2 OCCURS 0,
      PRITEM LIKE BAPIMEREQITEM OCCURS 0,
      PRACCOUNT LIKE BAPIMEREQACCOUNT OCCURS 0,
      PRADDRDELIVERY LIKE BAPIMERQADDRDELIVERY OCCURS 0,
      PRITEMTEXT LIKE BAPIMEREQITEMTEXT OCCURS 0,
      PRHEADERTEXT LIKE BAPIMEREQHEADTEXT OCCURS 0,
      EXTENSIONOUT LIKE BAPIPAREX OCCURS 0,
      ALLVERSIONS LIKE BAPIMEDCM_ALLVERSIONS OCCURS 0,
      SERIALNUMBERS LIKE BAPIMEREQSERIALNO OCCURS 0,
      PRCOMPONENTS LIKE BAPIMEREQCOMPONENT OCCURS 0,
      PRHEADER LIKE BAPIMEREQHEADER,
      SERVICEOUTLINE TYPE TABLE OF BAPI_SRV_OUTLINE,
      SERVICELINES TYPE TABLE OF BAPI_SRV_SERVICE_LINE,
      SERVICELIMIT TYPE TABLE OF BAPI_SRV_LIMIT_DATA,
      SERVICECONTRACTLIMITS TYPE TABLE OF BAPI_SRV_CONTRACT_LIMITS,
      SERVICEACCOUNT TYPE TABLE OF BAPI_SRV_ACC_DATA,
      SERVICELONGTEXTS TYPE TABLE OF BAPI_SRV_LONGTEXTS.
SWC_GET_ELEMENT CONTAINER 'AccountAssignment' ACCOUNTASSIGNMENT.
IF SY-SUBRC <> 0.
  MOVE SPACE TO ACCOUNTASSIGNMENT.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'ItemText' ITEMTEXT.
IF SY-SUBRC <> 0.
  MOVE SPACE TO ITEMTEXT.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'HeaderText' HEADERTEXT.
IF SY-SUBRC <> 0.
  MOVE SPACE TO HEADERTEXT.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'Version' VERSION.
IF SY-SUBRC <> 0.
  MOVE SPACE TO VERSION.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'DeliveryAddress' DELIVERYADDRESS.
IF SY-SUBRC <> 0.
  MOVE SPACE TO DELIVERYADDRESS.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'Components' COMPONENTS.
IF SY-SUBRC <> 0.
  MOVE SPACE TO COMPONENTS.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'SerialNumbers' SERIAL_NUMBERS.
IF SY-SUBRC <> 0.
  MOVE SPACE TO SERIAL_NUMBERS.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'Services' SERVICES.
IF SY-SUBRC <> 0.
  MOVE SPACE TO SERVICES.
ENDIF.
" Code Remediation changes S4 2025_1_A Conversion **BEGIN OF CHANGE BY SAP_ABAP 06.06.2026  FOR ATC
CALL FUNCTION 'BAPI_PR_GETDETAIL'"#EC CI_USAGE_OK[2438131]
" Code Remediation changes S4 2025_1_A Conversion * *END OF CHANGE BY SAP_ABAP 06.06.2026 FOR ATC
  EXPORTING
    NUMBER                = OBJECT-KEY-NUMBER
    ACCOUNT_ASSIGNMENT    = ACCOUNTASSIGNMENT
    ITEM_TEXT             = ITEMTEXT
    HEADER_TEXT           = HEADERTEXT
    DELIVERY_ADDRESS      = DELIVERYADDRESS
    SERIAL_NUMBERS        = SERIAL_NUMBERS
    SC_COMPONENTS         = COMPONENTS
    VERSION               = VERSION
    SERVICES              = SERVICES
  IMPORTING
    PRHEADER              = PRHEADER
  TABLES
    ALLVERSIONS           = ALLVERSIONS
    EXTENSIONOUT          = EXTENSIONOUT
    PRHEADERTEXT          = PRHEADERTEXT
    PRITEMTEXT            = PRITEMTEXT
    PRADDRDELIVERY        = PRADDRDELIVERY
    PRACCOUNT             = PRACCOUNT
    SERIALNUMBERS         = SERIALNUMBERS
    PRCOMPONENTS          = PRCOMPONENTS
    SERVICEOUTLINE        = SERVICEOUTLINE
    SERVICELINES          = SERVICELINES
    SERVICELIMIT          = SERVICELIMIT
    SERVICECONTRACTLIMITS = SERVICECONTRACTLIMITS
    SERVICEACCOUNT        = SERVICEACCOUNT
    SERVICELONGTEXTS      = SERVICELONGTEXTS
    PRITEM                = PRITEM
    RETURN                = RETURN
  EXCEPTIONS
    OTHERS                = 0.
SWC_SET_TABLE CONTAINER 'Return' RETURN.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'PrItem' PRITEM.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'PrAccount' PRACCOUNT.
SWC_SET_TABLE CONTAINER 'PrAddrDelivery' PRADDRDELIVERY.
SWC_SET_TABLE CONTAINER 'PrItemText' PRITEMTEXT.
SWC_SET_TABLE CONTAINER 'PrHeaderText' PRHEADERTEXT.
SWC_SET_TABLE CONTAINER 'Extensionout' EXTENSIONOUT.
SWC_SET_TABLE CONTAINER 'AllVersions' ALLVERSIONS.
SWC_SET_TABLE CONTAINER 'PRSerialNumbers' SERIALNUMBERS.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'PrComponents' PRCOMPONENTS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_ELEMENT CONTAINER 'PrHeader' PRHEADER.
SWC_SET_TABLE CONTAINER 'ServiceOutline' SERVICEOUTLINE.
SWC_SET_TABLE CONTAINER 'ServiceLines' SERVICELINES.
SWC_SET_TABLE CONTAINER 'ServiceLimit'  SERVICELIMIT.
SWC_SET_TABLE CONTAINER 'ServiceContractLimits' SERVICECONTRACTLIMITS.
SWC_SET_TABLE CONTAINER 'ServiceAccount' SERVICEACCOUNT.
SWC_SET_TABLE CONTAINER 'ServiceLongtexts' SERVICELONGTEXTS.
END_METHOD.

BEGIN_METHOD CONFIRM CHANGING CONTAINER.
DATA: LV_BANFN LIKE OBJECT-KEY-NUMBER,
      CONFIRM(255).
SWC_SET_ELEMENT CONTAINER RESULT CONFIRM.

SELECT BANFN FROM EBAN INTO LV_BANFN
                       WHERE BANFN EQ OBJECT-KEY-NUMBER.
ENDSELECT.
IF SY-SUBRC NE 0.
  EXIT_OBJECT_NOT_FOUND.
ENDIF.
END_METHOD.

BEGIN_METHOD GETITEMS CHANGING CONTAINER.
DATA:
      PREQNO TYPE BAPIEBAN-PREQ_NO,
      PURGROUP TYPE BAPIEBAN-PUR_GROUP,
      PREQNAME TYPE BAPIEBAN-PREQ_NAME,
      PREQDATE TYPE BAPIEBAN-PREQ_DATE,
      MATERIAL TYPE BAPIEBAN-MATERIAL,
      MATGRP TYPE BAPIEBAN-MAT_GRP,
      TRACKINGNO TYPE BAPIEBAN-TRACKINGNO,
      PLANT TYPE BAPIEBAN-PLANT,
      DOCTYPE TYPE BAPIEBAN-DOC_TYPE,
      DELIVDATE TYPE BAPIEBAN-DELIV_DATE,
      RELDATE TYPE BAPIEBAN-REL_DATE,
      SHORTTEXT TYPE BAPIEBAN-SHORT_TEXT,
      ASSIGNEDITEMS TYPE BAPIMMPARA-SELECTION,
      CLOSEDITEMS TYPE BAPIMMPARA-SELECTION,
      DELETEDITEMS TYPE BAPIMMPARA-SELECTION,
      PARTIALLYORDEREDITEMS TYPE BAPIMMPARA-SELECTION,
      ONLYNONMATERIALITEMS TYPE BAPIMMPARA-SELECTION,
      OPENITEMS TYPE BAPIMMPARA-SELECTION,
      REQUISITIONITEMS LIKE BAPIEBANC OCCURS 0,
      RETURN LIKE BAPIRETURN OCCURS 0,
      MATERIALEVG LIKE BAPIMGVMATNR.
SWC_GET_ELEMENT CONTAINER 'PreqNo' PREQNO.
SWC_GET_ELEMENT CONTAINER 'PurGroup' PURGROUP.
SWC_GET_ELEMENT CONTAINER 'PreqName' PREQNAME.
SWC_GET_ELEMENT CONTAINER 'PreqDate' PREQDATE.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_ELEMENT CONTAINER 'Material' MATERIAL.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_ELEMENT CONTAINER 'MatGrp' MATGRP.
SWC_GET_ELEMENT CONTAINER 'Trackingno' TRACKINGNO.
SWC_GET_ELEMENT CONTAINER 'Plant' PLANT.
SWC_GET_ELEMENT CONTAINER 'DocType' DOCTYPE.
SWC_GET_ELEMENT CONTAINER 'DelivDate' DELIVDATE.
SWC_GET_ELEMENT CONTAINER 'RelDate' RELDATE.
SWC_GET_ELEMENT CONTAINER 'ShortText' SHORTTEXT.
SWC_GET_ELEMENT CONTAINER 'AssignedItems' ASSIGNEDITEMS.
IF SY-SUBRC <> 0.
  MOVE SPACE TO ASSIGNEDITEMS.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'ClosedItems' CLOSEDITEMS.
IF SY-SUBRC <> 0.
  MOVE SPACE TO CLOSEDITEMS.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'DeletedItems' DELETEDITEMS.
IF SY-SUBRC <> 0.
  MOVE SPACE TO DELETEDITEMS.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'PartiallyOrderedItems'
     PARTIALLYORDEREDITEMS.
IF SY-SUBRC <> 0.
  MOVE SPACE TO PARTIALLYORDEREDITEMS.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'OnlyNonMaterialItems' ONLYNONMATERIALITEMS.
IF SY-SUBRC <> 0.
  MOVE SPACE TO ONLYNONMATERIALITEMS.
ENDIF.
SWC_GET_ELEMENT CONTAINER 'OpenItems' OPENITEMS.
IF SY-SUBRC <> 0.
  MOVE 'X' TO OPENITEMS.
ENDIF.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_TABLE CONTAINER 'RequisitionItems' REQUISITIONITEMS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_GET_ELEMENT CONTAINER 'materialEVG' MATERIALEVG.
" Code Remediation changes S4 2025_1_A Conversion **BEGIN OF CHANGE BY SAP_ABAP 06.06.2026  FOR ATC
CALL FUNCTION 'BAPI_REQUISITION_GETITEMS'"#EC CI_USAGE_OK[2438131]
" Code Remediation changes S4 2025_1_A Conversion * *END OF CHANGE BY SAP_ABAP 06.06.2026 FOR ATC
  EXPORTING
    MATERIAL_EVG            = MATERIALEVG
    OPEN_ITEMS              = OPENITEMS
    ONLY_NON_MATERIAL_ITEMS = ONLYNONMATERIALITEMS
    PARTIALLY_ORDERED_ITEMS = PARTIALLYORDEREDITEMS
    DELETED_ITEMS           = DELETEDITEMS
    CLOSED_ITEMS            = CLOSEDITEMS
    ASSIGNED_ITEMS          = ASSIGNEDITEMS
    SHORT_TEXT              = SHORTTEXT
    REL_DATE                = RELDATE
    DELIV_DATE              = DELIVDATE
    DOC_TYPE                = DOCTYPE
    PLANT                   = PLANT
    TRACKINGNO              = TRACKINGNO
    MAT_GRP                 = MATGRP
    MATERIAL                = MATERIAL
    PREQ_DATE               = PREQDATE
    PREQ_NAME               = PREQNAME
    PUR_GROUP               = PURGROUP
    PREQ_NO                 = PREQNO
  TABLES
    REQUISITION_ITEMS       = REQUISITIONITEMS
    RETURN                  = RETURN
  EXCEPTIONS
    OTHERS                  = 01.
CASE SY-SUBRC.
  WHEN 0.            " OK
  WHEN OTHERS.       " to be implemented
ENDCASE.
*--- BEGIN OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'RequisitionItems' REQUISITIONITEMS.  "#EC CI_FLDEXT_OK
*--- END OF CHANGE BY SAP_ABAP 08.08.2026 FOR ATC ---
SWC_SET_TABLE CONTAINER 'Return' RETURN.
END_METHOD.

BEGIN_METHOD DISPLAYERRORLOG CHANGING CONTAINER.
* define local data objects
DATA:
  LV_LOGHANDLE TYPE BALHANDLE-LOG_HANDLE,
  LT_LOGHANDLE TYPE BAL_T_LOGH.

* get imported application log handle
SWC_GET_ELEMENT CONTAINER 'LOGHANDLE' LV_LOGHANDLE.
INSERT LV_LOGHANDLE INTO TABLE LT_LOGHANDLE.

CALL FUNCTION 'BAL_DSP_LOG_DISPLAY'
  EXPORTING
    I_T_LOG_HANDLE       = LT_LOGHANDLE
    I_AMODAL             = 'X'
  EXCEPTIONS
    PROFILE_INCONSISTENT = 1
    INTERNAL_ERROR       = 2
    NO_DATA_AVAILABLE    = 3
    NO_AUTHORITY         = 4
    OTHERS               = 5.
IF SY-SUBRC <> 0.
  MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
          WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.

END_METHOD.


BEGIN_METHOD FETCH_APPROVER_WF CHANGING CONTAINER.
DATA:
      SLNO TYPE ZMM_PURCH-SLNO,
      INITIATOROFWORKFLOWI TYPE WFSYST-INITIATOR OCCURS 0,
      PURCHASEREQUISITION TYPE EBAN-BANFN,
      END_FLAG TYPE SYST-PRI40,
      DIR_APP TYPE WFSYST-INITIATOR.
SWC_GET_ELEMENT CONTAINER 'SLNO' SLNO.
SWC_GET_ELEMENT CONTAINER 'PurchaseRequisition' PURCHASEREQUISITION.

SWC_GET_ELEMENT CONTAINER 'dir_app' DIR_APP.
*do.
*
*  enddo.

WAIT up to 2 seconds.

DATA: IT_ZMM_PURCH TYPE TABLE OF ZMM_PURCH,
      IT_ZMM_PURCH1 TYPE TABLE OF ZMM_PURCH,
      WA_ZMM_PURCH TYPE ZMM_PURCH,
         WA_ZMM_PURCH1 TYPE ZMM_PURCH,
              USER TYPE WFSYST-INITIATOR.

IF DIR_APP IS INITIAL.
*end_flag = 'X'.


*        USER TYPE WFSYST-INITIATOR.
  CONDENSE SLNO.
  SELECT * INTO TABLE IT_ZMM_PURCH
    FROM ZMM_PURCH
    WHERE
    SLNO = SLNO
    AND
    BANFN = PURCHASEREQUISITION.
  IF SY-SUBRC = 0.
     SELECT * APPENDING TABLE   IT_ZMM_PURCH1
    FROM ZMM_PURCH
    WHERE
    SLNO = 'DIR'
    AND
    BANFN = PURCHASEREQUISITION.
*       and
*       status <> 'REVERT'.
    if sy-subrc = 0.
    sort IT_ZMM_PURCH1 by cdate ctime DESCENDING.
    endif.
    LOOP AT IT_ZMM_PURCH INTO WA_ZMM_PURCH.
     read table IT_ZMM_PURCH1 into wa_ZMM_PURCH1 index 1.
     if sy-subrc = 0 and wa_ZMM_PURCH1-cdate >= wa_ZMM_PURCH-cdate and wa_ZMM_PURCH1-ctime > wa_ZMM_PURCH-ctime.
       move wa_ZMM_PURCH1 to wa_ZMM_PURCH.
       endif.
      CONCATENATE 'US' WA_ZMM_PURCH-OBJID INTO USER.
*INITIATOROFWORKFLOWI.
      APPEND USER TO INITIATOROFWORKFLOWI.
      WA_ZMM_PURCH-STATUS = 'PENDING'.
      MODIFY ZMM_PURCH FROM WA_ZMM_PURCH.
      exit.
    ENDLOOP.
  ELSE.
    SLNO = SLNO + 1.
    CONDENSE SLNO.
    SELECT * INTO TABLE IT_ZMM_PURCH
FROM ZMM_PURCH
WHERE
SLNO <> SLNO
AND
BANFN = PURCHASEREQUISITION.
    IF SY-SUBRC = 0.
      SORT IT_ZMM_PURCH BY ctime cdate DESCENDING.
      READ TABLE IT_ZMM_PURCH INTO WA_ZMM_PURCH1 INDEX 1.

      IF WA_ZMM_PURCH1-SLNO = 'DIR'.
        END_FLAG = 'X'.
      ENDIF.


      LOOP AT IT_ZMM_PURCH INTO WA_ZMM_PURCH WHERE SLNO = WA_ZMM_PURCH1-SLNO.
        CONCATENATE 'US' WA_ZMM_PURCH-OBJID INTO USER.
*INITIATOROFWORKFLOWI.
        APPEND USER TO INITIATOROFWORKFLOWI.
        WA_ZMM_PURCH-STATUS = 'PENDING'.
        WA_ZMM_PURCH-CDATE  = SY-DATUM.
        WA_ZMM_PURCH-CTIME = SY-UZEIT.
        MODIFY ZMM_PURCH FROM WA_ZMM_PURCH.
      ENDLOOP.
    ENDIF.

*      select * into TABLE it_ZMM_PURCH
*    from ZMM_PURCH
*    where
*    slno = 'DIR'
*    and
*    banfn = PURCHASEREQUISITION.
*    if sy-subrc = 0.
*      LOOP AT it_ZMM_PURCH INTO WA_ZMM_PURCH.
*CONCATENATE 'US' WA_ZMM_PURCH-OBJID INTO USER.
**INITIATOROFWORKFLOWI.
*APPEND USER TO INITIATOROFWORKFLOWI.
*wa_ZMM_PURCH-status = 'PENDING'.
*modify ZMM_PURCH from wa_ZMM_PURCH.
*    ENDLOOP.
*    end_flag = 'X'.
*slno = slno - 1.
*CONDENSE slno.
*    else.
*    slno = slno - 1.
*    CONDENSE slno.
*     select * into TABLE it_ZMM_PURCH
*    from ZMM_PURCH
*    where
*    slno = slno
*    and
*    banfn = PURCHASEREQUISITION.
*IF SY-SUBRC = 0.
*  LOOP AT it_ZMM_PURCH INTO WA_ZMM_PURCH.
*CONCATENATE 'US' WA_ZMM_PURCH-OBJID INTO USER.
**INITIATOROFWORKFLOWI.
*APPEND USER TO INITIATOROFWORKFLOWI.
*wa_ZMM_PURCH-status = 'PENDING'.
*modify ZMM_PURCH from wa_ZMM_PURCH.
*
* CALL FUNCTION 'ZMM_PR_RELEASE'
*    EXPORTING
*      NAME          = WA_ZMM_PURCH-OBJID
*      WBANFN        = PURCHASEREQUISITION
*      W_FLAG        = 'D'.
*
*    ENDLOOP.
*    endif.
*
*
*    endif.
  ENDIF.


ELSE.
  SELECT SINGLE  * INTO  WA_ZMM_PURCH
   FROM ZMM_PURCH
   WHERE
   SLNO = '1'
   AND
   BANFN = PURCHASEREQUISITION.
  IF SY-SUBRC = 0.
*  LOOP AT it_ZMM_PURCH INTO WA_ZMM_PURCH.
*CONCATENATE 'US' dir_app INTO USER.
*INITIATOROFWORKFLOWI.
    REFRESH INITIATOROFWORKFLOWI.
    APPEND DIR_APP TO INITIATOROFWORKFLOWI.
    WA_ZMM_PURCH-STATUS = 'PENDING'.
    WA_ZMM_PURCH-OBJID = DIR_APP+2(12).
*CONCATENATE 'DIR' slno into wa_ZMM_PURCH-slno.
    CONDENSE SLNO.
    DATA : WA_AGR_USERS TYPE AGR_USERS..


    SELECT SINGLE * FROM AGR_USERS INTO WA_AGR_USERS
                          WHERE AGR_NAME IN ('D:MM_SRV_IND_APPROVE_DI',
                                             'MM_INDENT_ALL_PLANT_ONGC_DI',
                                             'MM_INV_RES_ALL_PLANT_ONGC_DI',
                                             'MM_PUR_PO_ALL_PLANT_ONGC_DI',
                                             'MM_SRV_SES_ALL_PLANT_ONGC_DI',
******* Start of added by anamika new role for OSD on 24.03.2015 RD1K996751"""
     'D:MM_SRV_IND_APPROVE_OSD',
**********End of added by anamika for OSD on 24.03.2015 RD1K996751*********
                                             'D:MM_SRV_IND_APPROVE_DF') AND
                                UNAME EQ DIR_APP+2(12).

    IF SY-SUBRC = 0.

      END_FLAG = 'X'.
      WA_ZMM_PURCH-SLNO = 'DIR'.
    ELSE.
      SELECT SINGLE  * INTO  WA_ZMM_PURCH1
     FROM ZMM_PURCH
     WHERE
     SLNO = SLNO
     AND
     BANFN = PURCHASEREQUISITION.
      IF SY-SUBRC <> 0.
        WA_ZMM_PURCH-SLNO = SLNO.
      ELSE.
        WA_ZMM_PURCH-SLNO = SLNO + 1.
        CONDENSE WA_ZMM_PURCH-SLNO.
      ENDIF.
    ENDIF.
*wa_ZMM_PURCH-status = 'PENDING'.
*
    WA_ZMM_PURCH-CDATE  = SY-DATUM.
    WA_ZMM_PURCH-CTIME = SY-UZEIT.
    INSERT ZMM_PURCH FROM WA_ZMM_PURCH.
*wa_ZMM_PURCH-slno = 'DIE
*modify ZMM_PURCH from wa_ZMM_PURCH.
*    ENDLOOP.




  ENDIF.
ENDIF.



SWC_SET_ELEMENT CONTAINER 'SLNO' SLNO.
SWC_SET_TABLE CONTAINER 'InitiatorOfWorkflowI' INITIATOROFWORKFLOWI.
SWC_SET_ELEMENT CONTAINER 'END_FLAG' END_FLAG.
END_METHOD.

BEGIN_METHOD SEND_MAIL CHANGING CONTAINER.
DATA:
      APPROVER TYPE WFSYST-INITIATOR OCCURS 0,
      CREATOR TYPE WFSYST-INITIATOR,
      PURCHASEREQUISITION TYPE EBAN-BANFN,
      FLAG TYPE SYST-PRI40.
SWC_GET_TABLE CONTAINER 'approver' APPROVER.
SWC_GET_ELEMENT CONTAINER 'creator' CREATOR.
SWC_GET_ELEMENT CONTAINER 'PurchaseRequisition' PURCHASEREQUISITION.
SWC_GET_ELEMENT CONTAINER 'flag' FLAG.


DATA L_NAME TYPE SY-UNAME.

*  if approver[] is INITIAL and creator is not INITIAL.
*    l_name = creator+2(12).
*  CALL FUNCTION 'ZMM_PR_RELEASE'
*    EXPORTING
*      NAME          = l_name
*      WBANFN        = PURCHASEREQUISITION
*      W_FLAG        = flag.
*            .
*endif.

IF APPROVER[] IS NOT INITIAL.
  LOOP AT APPROVER INTO CREATOR.
    L_NAME = CREATOR+2(12).
    CALL FUNCTION 'ZMM_PR_RELEASE'
      EXPORTING
        NAME   = L_NAME
        WBANFN = PURCHASEREQUISITION
        W_FLAG = FLAG.

  ENDLOOP.
ENDIF.

END_METHOD.

BEGIN_METHOD STATUS_ZMM_PURCH CHANGING CONTAINER.
DATA:
      PURCHASEREQUISITION TYPE ZMM_PURCH-BANFN,
      SNRO TYPE ZMM_PURCH-SLNO,
      FLAG TYPE SYST-PRI40.
SWC_GET_ELEMENT CONTAINER 'PurchaseRequisition' PURCHASEREQUISITION.
SWC_GET_ELEMENT CONTAINER 'snro' SNRO.
SWC_GET_ELEMENT CONTAINER 'flag' FLAG.

DATA: IT_ZMM_PURCH TYPE TABLE OF ZMM_PURCH,
      WA_ZMM_PURCH TYPE  ZMM_PURCH.

data IT_ZMM_PURCH1 TYPE TABLE OF ZMM_PURCH.

CONDENSE SNRO.

IF FLAG = 'B'.
  SNRO = 'DIR'.
ENDIF.

*  select * into TABLE it_ZMM_PURCH
*    from ZMM_PURCH
*    where
*    slno = snro
*    and
*    banfn = PURCHASEREQUISITION.
*    if sy-subrc <> 0.
SELECT * INTO TABLE IT_ZMM_PURCH
FROM ZMM_PURCH
WHERE
SLNO = SNRO
AND
BANFN = PURCHASEREQUISITION
  AND STATUS = 'PENDING'
  .
IF SY-SUBRC <> 0.
  SELECT * INTO TABLE IT_ZMM_PURCH
FROM ZMM_PURCH
WHERE
SLNO = 'DIR'
AND
BANFN = PURCHASEREQUISITION
    AND
    STATUS = 'PENDING'.
  IF SY-SUBRC = 0.
    SORT IT_ZMM_PURCH BY CDATE CTIME.
    DELETE ADJACENT DUPLICATES FROM IT_ZMM_PURCH COMPARING OBJID.
    else.
*      snro = snro - 1.
      SELECT * INTO TABLE IT_ZMM_PURCH
FROM ZMM_PURCH
WHERE
SLNO = SNRO
AND
BANFN = PURCHASEREQUISITION
  AND STATUS = 'PENDING'.

  ENDIF.

ENDIF.


  SELECT * INTO TABLE IT_ZMM_PURCH1
FROM ZMM_PURCH
WHERE
*SLNO = SNRO
*AND
BANFN = PURCHASEREQUISITION
  AND STATUS <> 'PENDING'.
    if sy-subrc = 0 and flag = 'V'.
sort IT_ZMM_PURCH1 by ctime cdate.

endif.

*endif.

*      endif.
IF IT_ZMM_PURCH[] IS NOT INITIAL.
  CASE FLAG.
    WHEN 'A'.
      LOOP AT IT_ZMM_PURCH INTO WA_ZMM_PURCH.
        WA_ZMM_PURCH-STATUS = 'FORWARDED'.
        MODIFY ZMM_PURCH FROM WA_ZMM_PURCH.
      ENDLOOP.

    WHEN 'R'.
      LOOP AT IT_ZMM_PURCH INTO WA_ZMM_PURCH.
        WA_ZMM_PURCH-STATUS = 'REJECTED'.
        MODIFY ZMM_PURCH FROM WA_ZMM_PURCH.
      ENDLOOP.

    WHEN 'V'.
      LOOP AT IT_ZMM_PURCH INTO WA_ZMM_PURCH.
        WA_ZMM_PURCH-STATUS = 'REVERT'.
        MODIFY ZMM_PURCH FROM WA_ZMM_PURCH.
      ENDLOOP.

wait UP TO 1 SECONDS.
read table IT_ZMM_PURCH1 into wa_zmm_purch index 1.
wa_zmm_purch-ctime = sy-uzeit.
wa_zmm_purch-cdate = sy-datum.
modify ZMM_PURCH from wa_ZMM_PURCH.


    WHEN 'B'.
      read table IT_ZMM_PURCH INTO WA_ZMM_PURCH with key status = 'PENDING'.
      if sy-subrc = 0.
      LOOP AT IT_ZMM_PURCH INTO WA_ZMM_PURCH.
        if WA_ZMM_PURCH-SlNO = 'DIR'.
        WA_ZMM_PURCH-STATUS = 'APPROVED'.
        else.
            WA_ZMM_PURCH-STATUS = 'FORWARDED'.
            endif.
        MODIFY ZMM_PURCH FROM WA_ZMM_PURCH.
      ENDLOOP.

      else.
         LOOP AT IT_ZMM_PURCH INTO WA_ZMM_PURCH.
               if WA_ZMM_PURCH-SlNO = 'DIR'.
             WA_ZMM_PURCH-STATUS = 'APPROVED'.
             else.
                   WA_ZMM_PURCH-STATUS = 'FORWARDED'.
               endif.
                MODIFY ZMM_PURCH FROM WA_ZMM_PURCH.
      ENDLOOP.
        endif.


* when 'B'.
*           loop at it_ZMM_PURCH into wa_ZMM_PURCH.
*            wa_ZMM_PURCH-status = 'APPROVED'.
*            modify ZMM_PURCH from wa_ZMM_PURCH.
*            ENDLOOP.


  ENDCASE.
ENDIF.

END_METHOD.

BEGIN_METHOD UPDATE_ZMM_MATNR_SET CHANGING CONTAINER.
DATA:
      PURCHASEREQUISITION TYPE EBAN-BANFN.
SWC_GET_ELEMENT CONTAINER 'PurchaseRequisition' PURCHASEREQUISITION.

DATA IT_EBAN TYPE TABLE OF EBAN.
DATA IT_EBAN1 TYPE TABLE OF EBAN.
DATA WA_EBAN TYPE EBAN.
DATA WA_EBAN1 TYPE EBAN.
DATA IT_ZMM_MATNR_SET TYPE TABLE OF ZMM_MATNR_SET.
DATA WA_ZMM_MATNR_SET TYPE ZMM_MATNR_SET.

DATA WA_ZMM_PURCH TYPE ZMM_PURCH.

" Code Remediation changes S4 2025_1_A Conversion **BEGIN OF CHANGE BY SAP_ABAP 06.06.2026  FOR ATC
*SELECT SINGLE * INTO WA_ZMM_PURCH
*  FROM ZMM_PURCH
*  WHERE
*  BANFN = PURCHASEREQUISITION
*  AND
*  STATUS = 'PENDING'.
 SELECT * FROM ZMM_PURCH   UP TO 1 ROWS INTO WA_ZMM_PURCH WHERE BANFN =
PURCHASEREQUISITION AND STATUS = 'PENDING'  ORDER BY  BANFN SLNO .
ENDSELECT.
" Code Remediation changes S4 2025_1_A Conversion * *END OF CHANGE BY SAP_ABAP 06.06.2026 FOR ATC
IF SY-SUBRC = 0.
  WA_ZMM_PURCH-STATUS = 'APPROVED'.
  MODIFY ZMM_PURCH FROM WA_ZMM_PURCH.
ENDIF.


SELECT * INTO TABLE IT_EBAN
  FROM EBAN
  WHERE
  BANFN = PURCHASEREQUISITION.

*  AND
*  ZZREL = 'X'.

IF SY-SUBRC = 0.
  sort it_eban by banfn matnr.
  move it_eban[] to it_eban1[].

*delete ADJACENT DUPLICATES FROM it_eban comparing banfn  matnr.


  LOOP AT IT_EBAN INTO WA_EBAN .
    clear WA_EBAN-MENGE.
    loop at it_eban1 into wa_eban1 where matnr = wa_eban-matnr.
      WA_EBAN-MENGE = WA_EBAN-MENGE + WA_EBAN1-MENGE.
      endloop.


    WA_ZMM_MATNR_SET-GJAHR = WA_EBAN-LFDAT(4).
    WA_ZMM_MATNR_SET-WERKS = WA_EBAN-WERKS.
    WA_ZMM_MATNR_SET-MATNR = WA_EBAN-MATNR.
    WA_ZMM_MATNR_SET-BANFN = WA_EBAN-BANFN.
    WA_ZMM_MATNR_SET-BNFPO = WA_EBAN-BNFPO.
    WA_ZMM_MATNR_SET-MENGE = WA_EBAN-MENGE.
    WA_ZMM_MATNR_SET-MEINS = WA_EBAN-MEINS.
    MODIFY ZMM_MATNR_SET FROM WA_ZMM_MATNR_SET.
    COMMIT WORK.
  ENDLOOP.

ENDIF.
END_METHOD.

BEGIN_METHOD ENTER_TEXT CHANGING CONTAINER.
DATA BANFN TYPE THEAD-TDNAME.

DATA IT_LINE TYPE TABLE OF TLINE.
DATA IT_LINE1 TYPE TABLE OF TLINE.
DATA WA_LINE TYPE TLINE.

DATA SYTITLE TYPE SYTITLE.
DATA IT_TAB TYPE CATSXT_LONGTEXT_ITAB.
DATA WA_TAB TYPE TXLINE.
BANFN = OBJECT-KEY-NUMBER.

CONCATENATE 'Comments for PR No' BANFN INTO SYTITLE SEPARATED BY SPACE.

CALL FUNCTION 'CATSXT_SIMPLE_TEXT_EDITOR'
  EXPORTING
    IM_TITLE        = SYTITLE
*   IM_DISPLAY_MODE = ' '
*   IM_START_COLUMN = 10
*   IM_START_ROW    = 10
  CHANGING
    CH_TEXT         = IT_TAB.


CLEAR WA_LINE.
APPEND WA_LINE TO IT_LINE.

DATA : L_DATE TYPE CHAR10,
      L_TIME TYPE CHAR8.

CONCATENATE SY-DATUM+6(2) '.' SY-DATUM+4(2) '.' SY-DATUM(4) INTO L_DATE.
CONCATENATE SY-UZEIT(2) '.' SY-UZEIT+2(2) '.' SY-UZEIT+4(2) INTO L_TIME.

CONCATENATE 'Reply' SY-UNAME  L_DATE L_TIME INTO WA_LINE-TDLINE SEPARATED BY SPACE.
APPEND WA_LINE TO IT_LINE.



CALL FUNCTION 'READ_TEXT'
  EXPORTING
*   CLIENT                        = SY-MANDT
    ID                            = 'ST'
    LANGUAGE                      = SY-LANGU
    NAME                          = BANFN
    OBJECT                        = 'TEXT'
*   ARCHIVE_HANDLE                = 0
*   LOCAL_CAT                     = ' '
* IMPORTING
*   HEADER                        =
*   OLD_LINE_COUNTER              =
  TABLES
    LINES                         = IT_LINE1
 EXCEPTIONS
   ID                            = 1
   LANGUAGE                      = 2
   NAME                          = 3
   NOT_FOUND                     = 4
   OBJECT                        = 5
   REFERENCE_CHECK               = 6
   WRONG_ACCESS_TO_ARCHIVE       = 7
   OTHERS                        = 8
          .
IF SY-SUBRC <> 0.
* Implement suitable error handling here
ENDIF.


CLEAR WA_LINE.
LOOP AT IT_TAB INTO WA_TAB.
  WA_LINE-TDLINE = WA_TAB.
  APPEND WA_LINE TO IT_LINE.
ENDLOOP.

APPEND LINES OF IT_LINE TO IT_LINE1.

DATA HEADER TYPE THEAD.

HEADER-TDOBJECT = 'TEXT'.
HEADER-TDNAME = BANFN.
HEADER-TDID = 'ST'.
HEADER-TDSPRAS = SY-LANGU.

CALL FUNCTION 'SAVE_TEXT'
  EXPORTING
*   CLIENT                = SY-MANDT
    HEADER                = HEADER
   INSERT                = 'X'
   SAVEMODE_DIRECT       = 'X'
*   OWNER_SPECIFIED       = ' '
*   LOCAL_CAT             = ' '
* IMPORTING
*   FUNCTION              =
*   NEWHEADER             =
  TABLES
    LINES                 = IT_LINE1
 EXCEPTIONS
   ID                    = 1
   LANGUAGE              = 2
   NAME                  = 3
   OBJECT                = 4
   OTHERS                = 5
          .
IF SY-SUBRC <> 0.
* Implement suitable error handling here
ELSE.
  COMMIT WORK.
ENDIF.


END_METHOD.




BEGIN_METHOD GET_DIR_APPROVER CHANGING CONTAINER.
DATA:
      INITIATOROFWORKFLOWI TYPE WFSYST-INITIATOR.

DATA USER TYPE SY-UNAME.

CALL FUNCTION 'ZUSER_GET_ID'
  IMPORTING
    BNAME = USER.
.
CONCATENATE  'US' USER INTO  INITIATOROFWORKFLOWI.


SWC_SET_ELEMENT CONTAINER 'InitiatorOfWorkflowI' INITIATOROFWORKFLOWI.
END_METHOD.

BEGIN_METHOD ZLOG_UPDATE CHANGING CONTAINER.
DATA:
      INITIATOROFWORKFLOWI TYPE WFSYST-INITIATOR OCCURS 0,
      banfn type banfn,
      status type SYPRI40.

  SWC_GET_TABLE CONTAINER 'InitiatorOfWorkflowI' INITIATOROFWORKFLOWI.
  swc_get_element container 'PR' banfn.
  swc_get_element container 'STATUS' status.

  data: it_ZMM_PURCH_LOG type TABLE OF ZMM_PURCH_LOG,
        wa_ZMM_PURCH_LOG type ZMM_PURCH_LOG,
        wa_agent type WFSYST-INITIATOR.

wa_ZMM_PURCH_LOG-slno = 0.


  select * into table it_ZMM_PURCH_LOG
    from ZMM_PURCH_LOG
    where
    banfn = banfn.
if sy-subrc = 0.
  sort it_ZMM_PURCH_LOG by slno DESCENDING.
  read table it_ZMM_PURCH_LOG into wa_ZMM_PURCH_LOG index 1.
  endif.


CASE STATUS.
  WHEN 'A'.
    wa_ZMM_PURCH_LOG-STATUS = 'APPROVED'.
    WHEN 'R'.
      wa_ZMM_PURCH_LOG-STATUS = 'REJECTED'.
      WHEN 'F'.
        wa_ZMM_PURCH_LOG-STATUS = 'FORWARDED'.
        when 'E'.
          wa_ZMM_PURCH_LOG-STATUS = 'REVERT'.
        ENDCASE.

wa_ZMM_PURCH_LOG-slno = wa_ZMM_PURCH_LOG-slno + 1.
loop at INITIATOROFWORKFLOWI into wa_agent.
wa_ZMM_PURCH_LOG-banfn = banfn.
wa_ZMM_PURCH_LOG-cdate = sy-datum.
wa_ZMM_PURCH_LOG-ctime = sy-uzeit.
wa_ZMM_PURCH_LOG-objid = wa_agent+2(12).
modify ZMM_PURCH_LOG from wa_ZMM_PURCH_LOG.

endloop.
commit WORK AND WAIT.
END_METHOD.

BEGIN_METHOD SEND_SMS CHANGING CONTAINER.
DATA:
      PURCHASEREQUISITION TYPE EBAN-BANFN,
      INITIATOROFWORKFLOWI TYPE WFSYST-INITIATOR OCCURS 0.
  SWC_GET_ELEMENT CONTAINER 'PurchaseRequisition' PURCHASEREQUISITION.
  SWC_GET_TABLE CONTAINER 'InitiatorOfWorkflowI' INITIATOROFWORKFLOWI.

  DATA PERSNO TYPE PERSNO.
  DATA USER TYPE WFSYST-INITIATOR.

READ TABLE INITIATOROFWORKFLOWI INTO USER INDEX 1.
  PERSNO = USER+2(12).

  CALL FUNCTION 'ZPR_APPROVAL_SMS'
   EXPORTING
     IM_EBELN       = PURCHASEREQUISITION
     IM_PERNR       = PERSNO
            .



END_METHOD.

BEGIN_METHOD SMS_APP CHANGING CONTAINER.
DATA:
      INITIATOROFWORKFLOWI TYPE WFSYST-INITIATOR,
      PURCHASEREQUISITION TYPE EBAN-BANFN.
  SWC_GET_ELEMENT CONTAINER 'InitiatorOfWorkflowI' INITIATOROFWORKFLOWI.
  SWC_GET_ELEMENT CONTAINER 'PurchaseRequisition' PURCHASEREQUISITION.

  data l_user type sy-uname.
  l_user = INITIATOROFWORKFLOWI+2(12).


  CALL FUNCTION 'ZPR_APPROVAL_SMS'
   EXPORTING
     IM_EBELN       = PURCHASEREQUISITION
     IM_PERNR       = l_user
     IM_FLAG        = 'X'
            .


END_METHOD.
